// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: notification/notification.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	EmailType     string                 `protobuf:"bytes,2,opt,name=email_type,json=emailType,proto3" json:"email_type,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendEmailRequest) GetEmailType() string {
	if x != nil {
		return x.EmailType
	}
	return ""
}

func (x *SendEmailRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetDeliveryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryStatusRequest) Reset() {
	*x = GetDeliveryStatusRequest{}
	mi := &file_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryStatusRequest) ProtoMessage() {}

func (x *GetDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeliveryStatusRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type GetDeliveryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	DeliveredAt   string                 `protobuf:"bytes,3,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryStatusResponse) Reset() {
	*x = GetDeliveryStatusResponse{}
	mi := &file_notification_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryStatusResponse) ProtoMessage() {}

func (x *GetDeliveryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryStatusResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeliveryStatusResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetDeliveryStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetDeliveryStatusResponse) GetDeliveredAt() string {
	if x != nil {
		return x.DeliveredAt
	}
	return ""
}

type GetPendingMobileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingMobileRequest) Reset() {
	*x = GetPendingMobileRequest{}
	mi := &file_notification_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingMobileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingMobileRequest) ProtoMessage() {}

func (x *GetPendingMobileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingMobileRequest.ProtoReflect.Descriptor instead.
func (*GetPendingMobileRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetPendingMobileRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MobileInboxEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChallengeId   uint64                 `protobuf:"varint,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	DisplayData   string                 `protobuf:"bytes,4,opt,name=display_data,json=displayData,proto3" json:"display_data,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MobileInboxEntry) Reset() {
	*x = MobileInboxEntry{}
	mi := &file_notification_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MobileInboxEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MobileInboxEntry) ProtoMessage() {}

func (x *MobileInboxEntry) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MobileInboxEntry.ProtoReflect.Descriptor instead.
func (*MobileInboxEntry) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{5}
}

func (x *MobileInboxEntry) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MobileInboxEntry) GetChallengeId() uint64 {
	if x != nil {
		return x.ChallengeId
	}
	return 0
}

func (x *MobileInboxEntry) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MobileInboxEntry) GetDisplayData() string {
	if x != nil {
		return x.DisplayData
	}
	return ""
}

func (x *MobileInboxEntry) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type PendingMobileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MobileInboxEntry    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingMobileResponse) Reset() {
	*x = PendingMobileResponse{}
	mi := &file_notification_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingMobileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingMobileResponse) ProtoMessage() {}

func (x *PendingMobileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingMobileResponse.ProtoReflect.Descriptor instead.
func (*PendingMobileResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{6}
}

func (x *PendingMobileResponse) GetItems() []*MobileInboxEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

type AckMobileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMobileRequest) Reset() {
	*x = AckMobileRequest{}
	mi := &file_notification_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMobileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMobileRequest) ProtoMessage() {}

func (x *AckMobileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMobileRequest.ProtoReflect.Descriptor instead.
func (*AckMobileRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{7}
}

func (x *AckMobileRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AckMobileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMobileResponse) Reset() {
	*x = AckMobileResponse{}
	mi := &file_notification_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMobileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMobileResponse) ProtoMessage() {}

func (x *AckMobileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMobileResponse.ProtoReflect.Descriptor instead.
func (*AckMobileResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{8}
}

func (x *AckMobileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_notification_notification_proto protoreflect.FileDescriptor

const file_notification_notification_proto_rawDesc = "" +
	"\n" +
	"\x1fnotification/notification.proto\x12\fnotification\"\xb8\x01\n" +
	"\x10SendEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x1d\n" +
	"\n" +
	"email_type\x18\x02 \x01(\tR\temailType\x12<\n" +
	"\x04data\x18\x03 \x03(\v2(.notification.SendEmailRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x11SendEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\x18GetDeliveryStatusRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"u\n" +
	"\x19GetDeliveryStatusResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fdelivered_at\x18\x03 \x01(\tR\vdeliveredAt\"2\n" +
	"\x17GetPendingMobileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x9f\x01\n" +
	"\x10MobileInboxEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fchallenge_id\x18\x02 \x01(\x04R\vchallengeId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12!\n" +
	"\fdisplay_data\x18\x04 \x01(\tR\vdisplayData\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tR\texpiresAt\"M\n" +
	"\x15PendingMobileResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.notification.MobileInboxEntryR\x05items\"\"\n" +
	"\x10AckMobileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"-\n" +
	"\x11AckMobileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x80\x03\n" +
	"\x13NotificationService\x12L\n" +
	"\tSendEmail\x12\x1e.notification.SendEmailRequest\x1a\x1f.notification.SendEmailResponse\x12d\n" +
	"\x11GetDeliveryStatus\x12&.notification.GetDeliveryStatusRequest\x1a'.notification.GetDeliveryStatusResponse\x12c\n" +
	"\x15GetPendingMobileItems\x12%.notification.GetPendingMobileRequest\x1a#.notification.PendingMobileResponse\x12P\n" +
	"\rAckMobileItem\x12\x1e.notification.AckMobileRequest\x1a\x1f.notification.AckMobileResponseB;Z9github.com/exbanka/contract/notificationpb;notificationpbb\x06proto3"

var (
	file_notification_notification_proto_rawDescOnce sync.Once
	file_notification_notification_proto_rawDescData []byte
)

func file_notification_notification_proto_rawDescGZIP() []byte {
	file_notification_notification_proto_rawDescOnce.Do(func() {
		file_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)))
	})
	return file_notification_notification_proto_rawDescData
}

var file_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_notification_notification_proto_goTypes = []any{
	(*SendEmailRequest)(nil),          // 0: notification.SendEmailRequest
	(*SendEmailResponse)(nil),         // 1: notification.SendEmailResponse
	(*GetDeliveryStatusRequest)(nil),  // 2: notification.GetDeliveryStatusRequest
	(*GetDeliveryStatusResponse)(nil), // 3: notification.GetDeliveryStatusResponse
	(*GetPendingMobileRequest)(nil),   // 4: notification.GetPendingMobileRequest
	(*MobileInboxEntry)(nil),          // 5: notification.MobileInboxEntry
	(*PendingMobileResponse)(nil),     // 6: notification.PendingMobileResponse
	(*AckMobileRequest)(nil),          // 7: notification.AckMobileRequest
	(*AckMobileResponse)(nil),         // 8: notification.AckMobileResponse
	nil,                               // 9: notification.SendEmailRequest.DataEntry
}
var file_notification_notification_proto_depIdxs = []int32{
	9, // 0: notification.SendEmailRequest.data:type_name -> notification.SendEmailRequest.DataEntry
	5, // 1: notification.PendingMobileResponse.items:type_name -> notification.MobileInboxEntry
	0, // 2: notification.NotificationService.SendEmail:input_type -> notification.SendEmailRequest
	2, // 3: notification.NotificationService.GetDeliveryStatus:input_type -> notification.GetDeliveryStatusRequest
	4, // 4: notification.NotificationService.GetPendingMobileItems:input_type -> notification.GetPendingMobileRequest
	7, // 5: notification.NotificationService.AckMobileItem:input_type -> notification.AckMobileRequest
	1, // 6: notification.NotificationService.SendEmail:output_type -> notification.SendEmailResponse
	3, // 7: notification.NotificationService.GetDeliveryStatus:output_type -> notification.GetDeliveryStatusResponse
	6, // 8: notification.NotificationService.GetPendingMobileItems:output_type -> notification.PendingMobileResponse
	8, // 9: notification.NotificationService.AckMobileItem:output_type -> notification.AckMobileResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_notification_notification_proto_init() }
func file_notification_notification_proto_init() {
	if File_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_notification_proto_goTypes,
		DependencyIndexes: file_notification_notification_proto_depIdxs,
		MessageInfos:      file_notification_notification_proto_msgTypes,
	}.Build()
	File_notification_notification_proto = out.File
	file_notification_notification_proto_goTypes = nil
	file_notification_notification_proto_depIdxs = nil
}
