// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: exchange/exchange.proto

package exchangepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRatesRequest) Reset() {
	*x = ListRatesRequest{}
	mi := &file_exchange_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRatesRequest) ProtoMessage() {}

func (x *ListRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRatesRequest.ProtoReflect.Descriptor instead.
func (*ListRatesRequest) Descriptor() ([]byte, []int) {
	return file_exchange_exchange_proto_rawDescGZIP(), []int{0}
}

type ListRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rates         []*RateResponse        `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRatesResponse) Reset() {
	*x = ListRatesResponse{}
	mi := &file_exchange_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRatesResponse) ProtoMessage() {}

func (x *ListRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRatesResponse.ProtoReflect.Descriptor instead.
func (*ListRatesResponse) Descriptor() ([]byte, []int) {
	return file_exchange_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *ListRatesResponse) GetRates() []*RateResponse {
	if x != nil {
		return x.Rates
	}
	return nil
}

type GetRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateRequest) Reset() {
	*x = GetRateRequest{}
	mi := &file_exchange_exchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateRequest) ProtoMessage() {}

func (x *GetRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_exchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateRequest.ProtoReflect.Descriptor instead.
func (*GetRateRequest) Descriptor() ([]byte, []int) {
	return file_exchange_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *GetRateRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *GetRateRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

type RateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	BuyRate       string                 `protobuf:"bytes,3,opt,name=buy_rate,json=buyRate,proto3" json:"buy_rate,omitempty"`
	SellRate      string                 `protobuf:"bytes,4,opt,name=sell_rate,json=sellRate,proto3" json:"sell_rate,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateResponse) Reset() {
	*x = RateResponse{}
	mi := &file_exchange_exchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateResponse) ProtoMessage() {}

func (x *RateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_exchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateResponse.ProtoReflect.Descriptor instead.
func (*RateResponse) Descriptor() ([]byte, []int) {
	return file_exchange_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *RateResponse) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *RateResponse) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *RateResponse) GetBuyRate() string {
	if x != nil {
		return x.BuyRate
	}
	return ""
}

func (x *RateResponse) GetSellRate() string {
	if x != nil {
		return x.SellRate
	}
	return ""
}

func (x *RateResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CalculateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateRequest) Reset() {
	*x = CalculateRequest{}
	mi := &file_exchange_exchange_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest) ProtoMessage() {}

func (x *CalculateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_exchange_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return file_exchange_exchange_proto_rawDescGZIP(), []int{4}
}

func (x *CalculateRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *CalculateRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *CalculateRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type CalculateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency    string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency      string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	InputAmount     string                 `protobuf:"bytes,3,opt,name=input_amount,json=inputAmount,proto3" json:"input_amount,omitempty"`
	ConvertedAmount string                 `protobuf:"bytes,4,opt,name=converted_amount,json=convertedAmount,proto3" json:"converted_amount,omitempty"`
	CommissionRate  string                 `protobuf:"bytes,5,opt,name=commission_rate,json=commissionRate,proto3" json:"commission_rate,omitempty"`
	EffectiveRate   string                 `protobuf:"bytes,6,opt,name=effective_rate,json=effectiveRate,proto3" json:"effective_rate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CalculateResponse) Reset() {
	*x = CalculateResponse{}
	mi := &file_exchange_exchange_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResponse) ProtoMessage() {}

func (x *CalculateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_exchange_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResponse.ProtoReflect.Descriptor instead.
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return file_exchange_exchange_proto_rawDescGZIP(), []int{5}
}

func (x *CalculateResponse) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *CalculateResponse) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *CalculateResponse) GetInputAmount() string {
	if x != nil {
		return x.InputAmount
	}
	return ""
}

func (x *CalculateResponse) GetConvertedAmount() string {
	if x != nil {
		return x.ConvertedAmount
	}
	return ""
}

func (x *CalculateResponse) GetCommissionRate() string {
	if x != nil {
		return x.CommissionRate
	}
	return ""
}

func (x *CalculateResponse) GetEffectiveRate() string {
	if x != nil {
		return x.EffectiveRate
	}
	return ""
}

type ConvertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertRequest) Reset() {
	*x = ConvertRequest{}
	mi := &file_exchange_exchange_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertRequest) ProtoMessage() {}

func (x *ConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_exchange_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertRequest.ProtoReflect.Descriptor instead.
func (*ConvertRequest) Descriptor() ([]byte, []int) {
	return file_exchange_exchange_proto_rawDescGZIP(), []int{6}
}

func (x *ConvertRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ConvertRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *ConvertRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type ConvertResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConvertedAmount string                 `protobuf:"bytes,1,opt,name=converted_amount,json=convertedAmount,proto3" json:"converted_amount,omitempty"`
	EffectiveRate   string                 `protobuf:"bytes,2,opt,name=effective_rate,json=effectiveRate,proto3" json:"effective_rate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConvertResponse) Reset() {
	*x = ConvertResponse{}
	mi := &file_exchange_exchange_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertResponse) ProtoMessage() {}

func (x *ConvertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_exchange_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertResponse.ProtoReflect.Descriptor instead.
func (*ConvertResponse) Descriptor() ([]byte, []int) {
	return file_exchange_exchange_proto_rawDescGZIP(), []int{7}
}

func (x *ConvertResponse) GetConvertedAmount() string {
	if x != nil {
		return x.ConvertedAmount
	}
	return ""
}

func (x *ConvertResponse) GetEffectiveRate() string {
	if x != nil {
		return x.EffectiveRate
	}
	return ""
}

var File_exchange_exchange_proto protoreflect.FileDescriptor

const file_exchange_exchange_proto_rawDesc = "" +
	"\n" +
	"\x17exchange/exchange.proto\x12\bexchange\"\x12\n" +
	"\x10ListRatesRequest\"A\n" +
	"\x11ListRatesResponse\x12,\n" +
	"\x05rates\x18\x01 \x03(\v2\x16.exchange.RateResponseR\x05rates\"V\n" +
	"\x0eGetRateRequest\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\"\xab\x01\n" +
	"\fRateResponse\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\x12\x19\n" +
	"\bbuy_rate\x18\x03 \x01(\tR\abuyRate\x12\x1b\n" +
	"\tsell_rate\x18\x04 \x01(\tR\bsellRate\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"p\n" +
	"\x10CalculateRequest\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"\xf7\x01\n" +
	"\x11CalculateResponse\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\x12!\n" +
	"\finput_amount\x18\x03 \x01(\tR\vinputAmount\x12)\n" +
	"\x10converted_amount\x18\x04 \x01(\tR\x0fconvertedAmount\x12'\n" +
	"\x0fcommission_rate\x18\x05 \x01(\tR\x0ecommissionRate\x12%\n" +
	"\x0eeffective_rate\x18\x06 \x01(\tR\reffectiveRate\"n\n" +
	"\x0eConvertRequest\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"c\n" +
	"\x0fConvertResponse\x12)\n" +
	"\x10converted_amount\x18\x01 \x01(\tR\x0fconvertedAmount\x12%\n" +
	"\x0eeffective_rate\x18\x02 \x01(\tR\reffectiveRate2\x9a\x02\n" +
	"\x0fExchangeService\x12D\n" +
	"\tListRates\x12\x1a.exchange.ListRatesRequest\x1a\x1b.exchange.ListRatesResponse\x12;\n" +
	"\aGetRate\x12\x18.exchange.GetRateRequest\x1a\x16.exchange.RateResponse\x12D\n" +
	"\tCalculate\x12\x1a.exchange.CalculateRequest\x1a\x1b.exchange.CalculateResponse\x12>\n" +
	"\aConvert\x12\x18.exchange.ConvertRequest\x1a\x19.exchange.ConvertResponseB3Z1github.com/exbanka/contract/exchangepb;exchangepbb\x06proto3"

var (
	file_exchange_exchange_proto_rawDescOnce sync.Once
	file_exchange_exchange_proto_rawDescData []byte
)

func file_exchange_exchange_proto_rawDescGZIP() []byte {
	file_exchange_exchange_proto_rawDescOnce.Do(func() {
		file_exchange_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exchange_exchange_proto_rawDesc), len(file_exchange_exchange_proto_rawDesc)))
	})
	return file_exchange_exchange_proto_rawDescData
}

var file_exchange_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_exchange_exchange_proto_goTypes = []any{
	(*ListRatesRequest)(nil),  // 0: exchange.ListRatesRequest
	(*ListRatesResponse)(nil), // 1: exchange.ListRatesResponse
	(*GetRateRequest)(nil),    // 2: exchange.GetRateRequest
	(*RateResponse)(nil),      // 3: exchange.RateResponse
	(*CalculateRequest)(nil),  // 4: exchange.CalculateRequest
	(*CalculateResponse)(nil), // 5: exchange.CalculateResponse
	(*ConvertRequest)(nil),    // 6: exchange.ConvertRequest
	(*ConvertResponse)(nil),   // 7: exchange.ConvertResponse
}
var file_exchange_exchange_proto_depIdxs = []int32{
	3, // 0: exchange.ListRatesResponse.rates:type_name -> exchange.RateResponse
	0, // 1: exchange.ExchangeService.ListRates:input_type -> exchange.ListRatesRequest
	2, // 2: exchange.ExchangeService.GetRate:input_type -> exchange.GetRateRequest
	4, // 3: exchange.ExchangeService.Calculate:input_type -> exchange.CalculateRequest
	6, // 4: exchange.ExchangeService.Convert:input_type -> exchange.ConvertRequest
	1, // 5: exchange.ExchangeService.ListRates:output_type -> exchange.ListRatesResponse
	3, // 6: exchange.ExchangeService.GetRate:output_type -> exchange.RateResponse
	5, // 7: exchange.ExchangeService.Calculate:output_type -> exchange.CalculateResponse
	7, // 8: exchange.ExchangeService.Convert:output_type -> exchange.ConvertResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_exchange_exchange_proto_init() }
func file_exchange_exchange_proto_init() {
	if File_exchange_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exchange_exchange_proto_rawDesc), len(file_exchange_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exchange_exchange_proto_goTypes,
		DependencyIndexes: file_exchange_exchange_proto_depIdxs,
		MessageInfos:      file_exchange_exchange_proto_msgTypes,
	}.Build()
	File_exchange_exchange_proto = out.File
	file_exchange_exchange_proto_goTypes = nil
	file_exchange_exchange_proto_depIdxs = nil
}
