// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: transaction/transaction.proto

package transactionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionService_CreatePayment_FullMethodName          = "/transaction.TransactionService/CreatePayment"
	TransactionService_ExecutePayment_FullMethodName         = "/transaction.TransactionService/ExecutePayment"
	TransactionService_GetPayment_FullMethodName             = "/transaction.TransactionService/GetPayment"
	TransactionService_ListPaymentsByAccount_FullMethodName  = "/transaction.TransactionService/ListPaymentsByAccount"
	TransactionService_ListPaymentsByClient_FullMethodName   = "/transaction.TransactionService/ListPaymentsByClient"
	TransactionService_CreateTransfer_FullMethodName         = "/transaction.TransactionService/CreateTransfer"
	TransactionService_ExecuteTransfer_FullMethodName        = "/transaction.TransactionService/ExecuteTransfer"
	TransactionService_GetTransfer_FullMethodName            = "/transaction.TransactionService/GetTransfer"
	TransactionService_ListTransfersByClient_FullMethodName  = "/transaction.TransactionService/ListTransfersByClient"
	TransactionService_CreatePaymentRecipient_FullMethodName = "/transaction.TransactionService/CreatePaymentRecipient"
	TransactionService_GetPaymentRecipient_FullMethodName    = "/transaction.TransactionService/GetPaymentRecipient"
	TransactionService_ListPaymentRecipients_FullMethodName  = "/transaction.TransactionService/ListPaymentRecipients"
	TransactionService_UpdatePaymentRecipient_FullMethodName = "/transaction.TransactionService/UpdatePaymentRecipient"
	TransactionService_DeletePaymentRecipient_FullMethodName = "/transaction.TransactionService/DeletePaymentRecipient"
)

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionServiceClient interface {
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	ExecutePayment(ctx context.Context, in *ExecutePaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	ListPaymentsByAccount(ctx context.Context, in *ListPaymentsByAccountRequest, opts ...grpc.CallOption) (*ListPaymentsResponse, error)
	ListPaymentsByClient(ctx context.Context, in *ListPaymentsByClientRequest, opts ...grpc.CallOption) (*ListPaymentsResponse, error)
	CreateTransfer(ctx context.Context, in *CreateTransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	ExecuteTransfer(ctx context.Context, in *ExecuteTransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	GetTransfer(ctx context.Context, in *GetTransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	ListTransfersByClient(ctx context.Context, in *ListTransfersByClientRequest, opts ...grpc.CallOption) (*ListTransfersResponse, error)
	CreatePaymentRecipient(ctx context.Context, in *CreatePaymentRecipientRequest, opts ...grpc.CallOption) (*PaymentRecipientResponse, error)
	GetPaymentRecipient(ctx context.Context, in *GetPaymentRecipientRequest, opts ...grpc.CallOption) (*PaymentRecipientResponse, error)
	ListPaymentRecipients(ctx context.Context, in *ListPaymentRecipientsRequest, opts ...grpc.CallOption) (*ListPaymentRecipientsResponse, error)
	UpdatePaymentRecipient(ctx context.Context, in *UpdatePaymentRecipientRequest, opts ...grpc.CallOption) (*PaymentRecipientResponse, error)
	DeletePaymentRecipient(ctx context.Context, in *DeletePaymentRecipientRequest, opts ...grpc.CallOption) (*DeletePaymentRecipientResponse, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, TransactionService_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ExecutePayment(ctx context.Context, in *ExecutePaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, TransactionService_ExecutePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ListPaymentsByAccount(ctx context.Context, in *ListPaymentsByAccountRequest, opts ...grpc.CallOption) (*ListPaymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymentsResponse)
	err := c.cc.Invoke(ctx, TransactionService_ListPaymentsByAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ListPaymentsByClient(ctx context.Context, in *ListPaymentsByClientRequest, opts ...grpc.CallOption) (*ListPaymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymentsResponse)
	err := c.cc.Invoke(ctx, TransactionService_ListPaymentsByClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) CreateTransfer(ctx context.Context, in *CreateTransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, TransactionService_CreateTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ExecuteTransfer(ctx context.Context, in *ExecuteTransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, TransactionService_ExecuteTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetTransfer(ctx context.Context, in *GetTransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ListTransfersByClient(ctx context.Context, in *ListTransfersByClientRequest, opts ...grpc.CallOption) (*ListTransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransfersResponse)
	err := c.cc.Invoke(ctx, TransactionService_ListTransfersByClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) CreatePaymentRecipient(ctx context.Context, in *CreatePaymentRecipientRequest, opts ...grpc.CallOption) (*PaymentRecipientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentRecipientResponse)
	err := c.cc.Invoke(ctx, TransactionService_CreatePaymentRecipient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetPaymentRecipient(ctx context.Context, in *GetPaymentRecipientRequest, opts ...grpc.CallOption) (*PaymentRecipientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentRecipientResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetPaymentRecipient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ListPaymentRecipients(ctx context.Context, in *ListPaymentRecipientsRequest, opts ...grpc.CallOption) (*ListPaymentRecipientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymentRecipientsResponse)
	err := c.cc.Invoke(ctx, TransactionService_ListPaymentRecipients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) UpdatePaymentRecipient(ctx context.Context, in *UpdatePaymentRecipientRequest, opts ...grpc.CallOption) (*PaymentRecipientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentRecipientResponse)
	err := c.cc.Invoke(ctx, TransactionService_UpdatePaymentRecipient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) DeletePaymentRecipient(ctx context.Context, in *DeletePaymentRecipientRequest, opts ...grpc.CallOption) (*DeletePaymentRecipientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePaymentRecipientResponse)
	err := c.cc.Invoke(ctx, TransactionService_DeletePaymentRecipient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
// All implementations must embed UnimplementedTransactionServiceServer
// for forward compatibility.
type TransactionServiceServer interface {
	CreatePayment(context.Context, *CreatePaymentRequest) (*PaymentResponse, error)
	ExecutePayment(context.Context, *ExecutePaymentRequest) (*PaymentResponse, error)
	GetPayment(context.Context, *GetPaymentRequest) (*PaymentResponse, error)
	ListPaymentsByAccount(context.Context, *ListPaymentsByAccountRequest) (*ListPaymentsResponse, error)
	ListPaymentsByClient(context.Context, *ListPaymentsByClientRequest) (*ListPaymentsResponse, error)
	CreateTransfer(context.Context, *CreateTransferRequest) (*TransferResponse, error)
	ExecuteTransfer(context.Context, *ExecuteTransferRequest) (*TransferResponse, error)
	GetTransfer(context.Context, *GetTransferRequest) (*TransferResponse, error)
	ListTransfersByClient(context.Context, *ListTransfersByClientRequest) (*ListTransfersResponse, error)
	CreatePaymentRecipient(context.Context, *CreatePaymentRecipientRequest) (*PaymentRecipientResponse, error)
	GetPaymentRecipient(context.Context, *GetPaymentRecipientRequest) (*PaymentRecipientResponse, error)
	ListPaymentRecipients(context.Context, *ListPaymentRecipientsRequest) (*ListPaymentRecipientsResponse, error)
	UpdatePaymentRecipient(context.Context, *UpdatePaymentRecipientRequest) (*PaymentRecipientResponse, error)
	DeletePaymentRecipient(context.Context, *DeletePaymentRecipientRequest) (*DeletePaymentRecipientResponse, error)
	mustEmbedUnimplementedTransactionServiceServer()
}

// UnimplementedTransactionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionServiceServer struct{}

func (UnimplementedTransactionServiceServer) CreatePayment(context.Context, *CreatePaymentRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedTransactionServiceServer) ExecutePayment(context.Context, *ExecutePaymentRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePayment not implemented")
}
func (UnimplementedTransactionServiceServer) GetPayment(context.Context, *GetPaymentRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayment not implemented")
}
func (UnimplementedTransactionServiceServer) ListPaymentsByAccount(context.Context, *ListPaymentsByAccountRequest) (*ListPaymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPaymentsByAccount not implemented")
}
func (UnimplementedTransactionServiceServer) ListPaymentsByClient(context.Context, *ListPaymentsByClientRequest) (*ListPaymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPaymentsByClient not implemented")
}
func (UnimplementedTransactionServiceServer) CreateTransfer(context.Context, *CreateTransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTransfer not implemented")
}
func (UnimplementedTransactionServiceServer) ExecuteTransfer(context.Context, *ExecuteTransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTransfer not implemented")
}
func (UnimplementedTransactionServiceServer) GetTransfer(context.Context, *GetTransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransfer not implemented")
}
func (UnimplementedTransactionServiceServer) ListTransfersByClient(context.Context, *ListTransfersByClientRequest) (*ListTransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTransfersByClient not implemented")
}
func (UnimplementedTransactionServiceServer) CreatePaymentRecipient(context.Context, *CreatePaymentRecipientRequest) (*PaymentRecipientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePaymentRecipient not implemented")
}
func (UnimplementedTransactionServiceServer) GetPaymentRecipient(context.Context, *GetPaymentRecipientRequest) (*PaymentRecipientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentRecipient not implemented")
}
func (UnimplementedTransactionServiceServer) ListPaymentRecipients(context.Context, *ListPaymentRecipientsRequest) (*ListPaymentRecipientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPaymentRecipients not implemented")
}
func (UnimplementedTransactionServiceServer) UpdatePaymentRecipient(context.Context, *UpdatePaymentRecipientRequest) (*PaymentRecipientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePaymentRecipient not implemented")
}
func (UnimplementedTransactionServiceServer) DeletePaymentRecipient(context.Context, *DeletePaymentRecipientRequest) (*DeletePaymentRecipientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePaymentRecipient not implemented")
}
func (UnimplementedTransactionServiceServer) mustEmbedUnimplementedTransactionServiceServer() {}
func (UnimplementedTransactionServiceServer) testEmbeddedByValue()                            {}

// UnsafeTransactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionServiceServer will
// result in compilation errors.
type UnsafeTransactionServiceServer interface {
	mustEmbedUnimplementedTransactionServiceServer()
}

func RegisterTransactionServiceServer(s grpc.ServiceRegistrar, srv TransactionServiceServer) {
	// If the following call panics, it indicates UnimplementedTransactionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionService_ServiceDesc, srv)
}

func _TransactionService_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ExecutePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ExecutePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ExecutePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ExecutePayment(ctx, req.(*ExecutePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetPayment(ctx, req.(*GetPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ListPaymentsByAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymentsByAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ListPaymentsByAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ListPaymentsByAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ListPaymentsByAccount(ctx, req.(*ListPaymentsByAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ListPaymentsByClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymentsByClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ListPaymentsByClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ListPaymentsByClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ListPaymentsByClient(ctx, req.(*ListPaymentsByClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_CreateTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CreateTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_CreateTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CreateTransfer(ctx, req.(*CreateTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ExecuteTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ExecuteTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ExecuteTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ExecuteTransfer(ctx, req.(*ExecuteTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetTransfer(ctx, req.(*GetTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ListTransfersByClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransfersByClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ListTransfersByClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ListTransfersByClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ListTransfersByClient(ctx, req.(*ListTransfersByClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_CreatePaymentRecipient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRecipientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CreatePaymentRecipient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_CreatePaymentRecipient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CreatePaymentRecipient(ctx, req.(*CreatePaymentRecipientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetPaymentRecipient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentRecipientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetPaymentRecipient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetPaymentRecipient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetPaymentRecipient(ctx, req.(*GetPaymentRecipientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ListPaymentRecipients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymentRecipientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ListPaymentRecipients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ListPaymentRecipients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ListPaymentRecipients(ctx, req.(*ListPaymentRecipientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_UpdatePaymentRecipient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaymentRecipientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).UpdatePaymentRecipient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_UpdatePaymentRecipient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).UpdatePaymentRecipient(ctx, req.(*UpdatePaymentRecipientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_DeletePaymentRecipient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePaymentRecipientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).DeletePaymentRecipient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_DeletePaymentRecipient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).DeletePaymentRecipient(ctx, req.(*DeletePaymentRecipientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionService_ServiceDesc is the grpc.ServiceDesc for TransactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePayment",
			Handler:    _TransactionService_CreatePayment_Handler,
		},
		{
			MethodName: "ExecutePayment",
			Handler:    _TransactionService_ExecutePayment_Handler,
		},
		{
			MethodName: "GetPayment",
			Handler:    _TransactionService_GetPayment_Handler,
		},
		{
			MethodName: "ListPaymentsByAccount",
			Handler:    _TransactionService_ListPaymentsByAccount_Handler,
		},
		{
			MethodName: "ListPaymentsByClient",
			Handler:    _TransactionService_ListPaymentsByClient_Handler,
		},
		{
			MethodName: "CreateTransfer",
			Handler:    _TransactionService_CreateTransfer_Handler,
		},
		{
			MethodName: "ExecuteTransfer",
			Handler:    _TransactionService_ExecuteTransfer_Handler,
		},
		{
			MethodName: "GetTransfer",
			Handler:    _TransactionService_GetTransfer_Handler,
		},
		{
			MethodName: "ListTransfersByClient",
			Handler:    _TransactionService_ListTransfersByClient_Handler,
		},
		{
			MethodName: "CreatePaymentRecipient",
			Handler:    _TransactionService_CreatePaymentRecipient_Handler,
		},
		{
			MethodName: "GetPaymentRecipient",
			Handler:    _TransactionService_GetPaymentRecipient_Handler,
		},
		{
			MethodName: "ListPaymentRecipients",
			Handler:    _TransactionService_ListPaymentRecipients_Handler,
		},
		{
			MethodName: "UpdatePaymentRecipient",
			Handler:    _TransactionService_UpdatePaymentRecipient_Handler,
		},
		{
			MethodName: "DeletePaymentRecipient",
			Handler:    _TransactionService_DeletePaymentRecipient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction/transaction.proto",
}

const (
	FeeService_ListFees_FullMethodName     = "/transaction.FeeService/ListFees"
	FeeService_CreateFee_FullMethodName    = "/transaction.FeeService/CreateFee"
	FeeService_UpdateFee_FullMethodName    = "/transaction.FeeService/UpdateFee"
	FeeService_DeleteFee_FullMethodName    = "/transaction.FeeService/DeleteFee"
	FeeService_CalculateFee_FullMethodName = "/transaction.FeeService/CalculateFee"
)

// FeeServiceClient is the client API for FeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeeServiceClient interface {
	ListFees(ctx context.Context, in *ListFeesRequest, opts ...grpc.CallOption) (*ListFeesResponse, error)
	CreateFee(ctx context.Context, in *CreateFeeRequest, opts ...grpc.CallOption) (*TransferFeeResponse, error)
	UpdateFee(ctx context.Context, in *UpdateFeeRequest, opts ...grpc.CallOption) (*TransferFeeResponse, error)
	DeleteFee(ctx context.Context, in *DeleteFeeRequest, opts ...grpc.CallOption) (*DeleteFeeResponse, error)
	CalculateFee(ctx context.Context, in *CalculateFeeRequest, opts ...grpc.CallOption) (*CalculateFeeResponse, error)
}

type feeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeeServiceClient(cc grpc.ClientConnInterface) FeeServiceClient {
	return &feeServiceClient{cc}
}

func (c *feeServiceClient) ListFees(ctx context.Context, in *ListFeesRequest, opts ...grpc.CallOption) (*ListFeesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeesResponse)
	err := c.cc.Invoke(ctx, FeeService_ListFees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feeServiceClient) CreateFee(ctx context.Context, in *CreateFeeRequest, opts ...grpc.CallOption) (*TransferFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferFeeResponse)
	err := c.cc.Invoke(ctx, FeeService_CreateFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feeServiceClient) UpdateFee(ctx context.Context, in *UpdateFeeRequest, opts ...grpc.CallOption) (*TransferFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferFeeResponse)
	err := c.cc.Invoke(ctx, FeeService_UpdateFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feeServiceClient) DeleteFee(ctx context.Context, in *DeleteFeeRequest, opts ...grpc.CallOption) (*DeleteFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFeeResponse)
	err := c.cc.Invoke(ctx, FeeService_DeleteFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feeServiceClient) CalculateFee(ctx context.Context, in *CalculateFeeRequest, opts ...grpc.CallOption) (*CalculateFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateFeeResponse)
	err := c.cc.Invoke(ctx, FeeService_CalculateFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeeServiceServer is the server API for FeeService service.
// All implementations must embed UnimplementedFeeServiceServer
// for forward compatibility.
type FeeServiceServer interface {
	ListFees(context.Context, *ListFeesRequest) (*ListFeesResponse, error)
	CreateFee(context.Context, *CreateFeeRequest) (*TransferFeeResponse, error)
	UpdateFee(context.Context, *UpdateFeeRequest) (*TransferFeeResponse, error)
	DeleteFee(context.Context, *DeleteFeeRequest) (*DeleteFeeResponse, error)
	CalculateFee(context.Context, *CalculateFeeRequest) (*CalculateFeeResponse, error)
	mustEmbedUnimplementedFeeServiceServer()
}

// UnimplementedFeeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeeServiceServer struct{}

func (UnimplementedFeeServiceServer) ListFees(context.Context, *ListFeesRequest) (*ListFeesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFees not implemented")
}
func (UnimplementedFeeServiceServer) CreateFee(context.Context, *CreateFeeRequest) (*TransferFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFee not implemented")
}
func (UnimplementedFeeServiceServer) UpdateFee(context.Context, *UpdateFeeRequest) (*TransferFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFee not implemented")
}
func (UnimplementedFeeServiceServer) DeleteFee(context.Context, *DeleteFeeRequest) (*DeleteFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFee not implemented")
}
func (UnimplementedFeeServiceServer) CalculateFee(context.Context, *CalculateFeeRequest) (*CalculateFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateFee not implemented")
}
func (UnimplementedFeeServiceServer) mustEmbedUnimplementedFeeServiceServer() {}
func (UnimplementedFeeServiceServer) testEmbeddedByValue()                    {}

// UnsafeFeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeeServiceServer will
// result in compilation errors.
type UnsafeFeeServiceServer interface {
	mustEmbedUnimplementedFeeServiceServer()
}

func RegisterFeeServiceServer(s grpc.ServiceRegistrar, srv FeeServiceServer) {
	// If the following call panics, it indicates UnimplementedFeeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeeService_ServiceDesc, srv)
}

func _FeeService_ListFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeeServiceServer).ListFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeeService_ListFees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeeServiceServer).ListFees(ctx, req.(*ListFeesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeeService_CreateFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeeServiceServer).CreateFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeeService_CreateFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeeServiceServer).CreateFee(ctx, req.(*CreateFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeeService_UpdateFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeeServiceServer).UpdateFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeeService_UpdateFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeeServiceServer).UpdateFee(ctx, req.(*UpdateFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeeService_DeleteFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeeServiceServer).DeleteFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeeService_DeleteFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeeServiceServer).DeleteFee(ctx, req.(*DeleteFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeeService_CalculateFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeeServiceServer).CalculateFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeeService_CalculateFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeeServiceServer).CalculateFee(ctx, req.(*CalculateFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeeService_ServiceDesc is the grpc.ServiceDesc for FeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.FeeService",
	HandlerType: (*FeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFees",
			Handler:    _FeeService_ListFees_Handler,
		},
		{
			MethodName: "CreateFee",
			Handler:    _FeeService_CreateFee_Handler,
		},
		{
			MethodName: "UpdateFee",
			Handler:    _FeeService_UpdateFee_Handler,
		},
		{
			MethodName: "DeleteFee",
			Handler:    _FeeService_DeleteFee_Handler,
		},
		{
			MethodName: "CalculateFee",
			Handler:    _FeeService_CalculateFee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction/transaction.proto",
}

const (
	InterBankService_InitiateInterBankTransfer_FullMethodName = "/transaction.InterBankService/InitiateInterBankTransfer"
	InterBankService_HandlePrepare_FullMethodName             = "/transaction.InterBankService/HandlePrepare"
	InterBankService_HandleCommit_FullMethodName              = "/transaction.InterBankService/HandleCommit"
	InterBankService_HandleCheckStatus_FullMethodName         = "/transaction.InterBankService/HandleCheckStatus"
	InterBankService_GetInterBankTransfer_FullMethodName      = "/transaction.InterBankService/GetInterBankTransfer"
	InterBankService_ReverseInterBankTransfer_FullMethodName  = "/transaction.InterBankService/ReverseInterBankTransfer"
)

// InterBankServiceClient is the client API for InterBankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Inter-bank 2PC transfer service (Spec 3).
type InterBankServiceClient interface {
	// Sender side — invoked by api-gateway when a client posts to
	// /api/v1/transfers with a receiver-account whose 3-digit prefix is not
	// OWN_BANK_CODE.
	InitiateInterBankTransfer(ctx context.Context, in *InitiateInterBankRequest, opts ...grpc.CallOption) (*InitiateInterBankResponse, error)
	// Receiver side — three handlers, one per inbound HTTP route forwarded
	// from api-gateway after HMAC verification.
	HandlePrepare(ctx context.Context, in *InterBankPrepareRequest, opts ...grpc.CallOption) (*InterBankPrepareResponse, error)
	HandleCommit(ctx context.Context, in *InterBankCommitRequest, opts ...grpc.CallOption) (*InterBankCommitResponse, error)
	HandleCheckStatus(ctx context.Context, in *InterBankCheckStatusRequest, opts ...grpc.CallOption) (*InterBankCheckStatusResponse, error)
	// Read-side helper used by the public GET /api/v1/me/transfers/{id}
	// route to render an inter-bank transfer's state.
	GetInterBankTransfer(ctx context.Context, in *GetInterBankTransferRequest, opts ...grpc.CallOption) (*GetInterBankTransferResponse, error)
	// Spec 4 / Celina 5 addendum: REVERSE_TRANSFER. Reuses the existing
	// PREPARE/COMMIT machinery on the opposite direction. Used by the
	// cross-bank OTC accept saga's compensation path when seller-side
	// ownership transfer fails after the buyer's funds have already moved.
	ReverseInterBankTransfer(ctx context.Context, in *ReverseInterBankTransferRequest, opts ...grpc.CallOption) (*ReverseInterBankTransferResponse, error)
}

type interBankServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInterBankServiceClient(cc grpc.ClientConnInterface) InterBankServiceClient {
	return &interBankServiceClient{cc}
}

func (c *interBankServiceClient) InitiateInterBankTransfer(ctx context.Context, in *InitiateInterBankRequest, opts ...grpc.CallOption) (*InitiateInterBankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateInterBankResponse)
	err := c.cc.Invoke(ctx, InterBankService_InitiateInterBankTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interBankServiceClient) HandlePrepare(ctx context.Context, in *InterBankPrepareRequest, opts ...grpc.CallOption) (*InterBankPrepareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterBankPrepareResponse)
	err := c.cc.Invoke(ctx, InterBankService_HandlePrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interBankServiceClient) HandleCommit(ctx context.Context, in *InterBankCommitRequest, opts ...grpc.CallOption) (*InterBankCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterBankCommitResponse)
	err := c.cc.Invoke(ctx, InterBankService_HandleCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interBankServiceClient) HandleCheckStatus(ctx context.Context, in *InterBankCheckStatusRequest, opts ...grpc.CallOption) (*InterBankCheckStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterBankCheckStatusResponse)
	err := c.cc.Invoke(ctx, InterBankService_HandleCheckStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interBankServiceClient) GetInterBankTransfer(ctx context.Context, in *GetInterBankTransferRequest, opts ...grpc.CallOption) (*GetInterBankTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInterBankTransferResponse)
	err := c.cc.Invoke(ctx, InterBankService_GetInterBankTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interBankServiceClient) ReverseInterBankTransfer(ctx context.Context, in *ReverseInterBankTransferRequest, opts ...grpc.CallOption) (*ReverseInterBankTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReverseInterBankTransferResponse)
	err := c.cc.Invoke(ctx, InterBankService_ReverseInterBankTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterBankServiceServer is the server API for InterBankService service.
// All implementations must embed UnimplementedInterBankServiceServer
// for forward compatibility.
//
// Inter-bank 2PC transfer service (Spec 3).
type InterBankServiceServer interface {
	// Sender side — invoked by api-gateway when a client posts to
	// /api/v1/transfers with a receiver-account whose 3-digit prefix is not
	// OWN_BANK_CODE.
	InitiateInterBankTransfer(context.Context, *InitiateInterBankRequest) (*InitiateInterBankResponse, error)
	// Receiver side — three handlers, one per inbound HTTP route forwarded
	// from api-gateway after HMAC verification.
	HandlePrepare(context.Context, *InterBankPrepareRequest) (*InterBankPrepareResponse, error)
	HandleCommit(context.Context, *InterBankCommitRequest) (*InterBankCommitResponse, error)
	HandleCheckStatus(context.Context, *InterBankCheckStatusRequest) (*InterBankCheckStatusResponse, error)
	// Read-side helper used by the public GET /api/v1/me/transfers/{id}
	// route to render an inter-bank transfer's state.
	GetInterBankTransfer(context.Context, *GetInterBankTransferRequest) (*GetInterBankTransferResponse, error)
	// Spec 4 / Celina 5 addendum: REVERSE_TRANSFER. Reuses the existing
	// PREPARE/COMMIT machinery on the opposite direction. Used by the
	// cross-bank OTC accept saga's compensation path when seller-side
	// ownership transfer fails after the buyer's funds have already moved.
	ReverseInterBankTransfer(context.Context, *ReverseInterBankTransferRequest) (*ReverseInterBankTransferResponse, error)
	mustEmbedUnimplementedInterBankServiceServer()
}

// UnimplementedInterBankServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInterBankServiceServer struct{}

func (UnimplementedInterBankServiceServer) InitiateInterBankTransfer(context.Context, *InitiateInterBankRequest) (*InitiateInterBankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateInterBankTransfer not implemented")
}
func (UnimplementedInterBankServiceServer) HandlePrepare(context.Context, *InterBankPrepareRequest) (*InterBankPrepareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandlePrepare not implemented")
}
func (UnimplementedInterBankServiceServer) HandleCommit(context.Context, *InterBankCommitRequest) (*InterBankCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleCommit not implemented")
}
func (UnimplementedInterBankServiceServer) HandleCheckStatus(context.Context, *InterBankCheckStatusRequest) (*InterBankCheckStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleCheckStatus not implemented")
}
func (UnimplementedInterBankServiceServer) GetInterBankTransfer(context.Context, *GetInterBankTransferRequest) (*GetInterBankTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterBankTransfer not implemented")
}
func (UnimplementedInterBankServiceServer) ReverseInterBankTransfer(context.Context, *ReverseInterBankTransferRequest) (*ReverseInterBankTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseInterBankTransfer not implemented")
}
func (UnimplementedInterBankServiceServer) mustEmbedUnimplementedInterBankServiceServer() {}
func (UnimplementedInterBankServiceServer) testEmbeddedByValue()                          {}

// UnsafeInterBankServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterBankServiceServer will
// result in compilation errors.
type UnsafeInterBankServiceServer interface {
	mustEmbedUnimplementedInterBankServiceServer()
}

func RegisterInterBankServiceServer(s grpc.ServiceRegistrar, srv InterBankServiceServer) {
	// If the following call panics, it indicates UnimplementedInterBankServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InterBankService_ServiceDesc, srv)
}

func _InterBankService_InitiateInterBankTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateInterBankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterBankServiceServer).InitiateInterBankTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterBankService_InitiateInterBankTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterBankServiceServer).InitiateInterBankTransfer(ctx, req.(*InitiateInterBankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterBankService_HandlePrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterBankPrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterBankServiceServer).HandlePrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterBankService_HandlePrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterBankServiceServer).HandlePrepare(ctx, req.(*InterBankPrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterBankService_HandleCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterBankCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterBankServiceServer).HandleCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterBankService_HandleCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterBankServiceServer).HandleCommit(ctx, req.(*InterBankCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterBankService_HandleCheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterBankCheckStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterBankServiceServer).HandleCheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterBankService_HandleCheckStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterBankServiceServer).HandleCheckStatus(ctx, req.(*InterBankCheckStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterBankService_GetInterBankTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterBankTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterBankServiceServer).GetInterBankTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterBankService_GetInterBankTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterBankServiceServer).GetInterBankTransfer(ctx, req.(*GetInterBankTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterBankService_ReverseInterBankTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseInterBankTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterBankServiceServer).ReverseInterBankTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterBankService_ReverseInterBankTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterBankServiceServer).ReverseInterBankTransfer(ctx, req.(*ReverseInterBankTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InterBankService_ServiceDesc is the grpc.ServiceDesc for InterBankService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterBankService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.InterBankService",
	HandlerType: (*InterBankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateInterBankTransfer",
			Handler:    _InterBankService_InitiateInterBankTransfer_Handler,
		},
		{
			MethodName: "HandlePrepare",
			Handler:    _InterBankService_HandlePrepare_Handler,
		},
		{
			MethodName: "HandleCommit",
			Handler:    _InterBankService_HandleCommit_Handler,
		},
		{
			MethodName: "HandleCheckStatus",
			Handler:    _InterBankService_HandleCheckStatus_Handler,
		},
		{
			MethodName: "GetInterBankTransfer",
			Handler:    _InterBankService_GetInterBankTransfer_Handler,
		},
		{
			MethodName: "ReverseInterBankTransfer",
			Handler:    _InterBankService_ReverseInterBankTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction/transaction.proto",
}
