// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: transaction/transaction.proto

package transactionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FromAccountNumber string                 `protobuf:"bytes,1,opt,name=from_account_number,json=fromAccountNumber,proto3" json:"from_account_number,omitempty"`
	ToAccountNumber   string                 `protobuf:"bytes,2,opt,name=to_account_number,json=toAccountNumber,proto3" json:"to_account_number,omitempty"`
	Amount            string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	RecipientName     string                 `protobuf:"bytes,4,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	PaymentCode       string                 `protobuf:"bytes,5,opt,name=payment_code,json=paymentCode,proto3" json:"payment_code,omitempty"`
	ReferenceNumber   string                 `protobuf:"bytes,6,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	PaymentPurpose    string                 `protobuf:"bytes,7,opt,name=payment_purpose,json=paymentPurpose,proto3" json:"payment_purpose,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetFromAccountNumber() string {
	if x != nil {
		return x.FromAccountNumber
	}
	return ""
}

func (x *CreatePaymentRequest) GetToAccountNumber() string {
	if x != nil {
		return x.ToAccountNumber
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreatePaymentRequest) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *CreatePaymentRequest) GetPaymentCode() string {
	if x != nil {
		return x.PaymentCode
	}
	return ""
}

func (x *CreatePaymentRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreatePaymentRequest) GetPaymentPurpose() string {
	if x != nil {
		return x.PaymentPurpose
	}
	return ""
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *GetPaymentRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListPaymentsByAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	DateFrom      string                 `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	StatusFilter  string                 `protobuf:"bytes,4,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	AmountMin     string                 `protobuf:"bytes,5,opt,name=amount_min,json=amountMin,proto3" json:"amount_min,omitempty"`
	AmountMax     string                 `protobuf:"bytes,6,opt,name=amount_max,json=amountMax,proto3" json:"amount_max,omitempty"`
	Page          int32                  `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsByAccountRequest) Reset() {
	*x = ListPaymentsByAccountRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsByAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsByAccountRequest) ProtoMessage() {}

func (x *ListPaymentsByAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsByAccountRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentsByAccountRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *ListPaymentsByAccountRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *ListPaymentsByAccountRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *ListPaymentsByAccountRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

func (x *ListPaymentsByAccountRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

func (x *ListPaymentsByAccountRequest) GetAmountMin() string {
	if x != nil {
		return x.AmountMin
	}
	return ""
}

func (x *ListPaymentsByAccountRequest) GetAmountMax() string {
	if x != nil {
		return x.AmountMax
	}
	return ""
}

func (x *ListPaymentsByAccountRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPaymentsByAccountRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*PaymentResponse     `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsResponse) Reset() {
	*x = ListPaymentsResponse{}
	mi := &file_transaction_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsResponse) ProtoMessage() {}

func (x *ListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *ListPaymentsResponse) GetPayments() []*PaymentResponse {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *ListPaymentsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PaymentResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromAccountNumber string                 `protobuf:"bytes,2,opt,name=from_account_number,json=fromAccountNumber,proto3" json:"from_account_number,omitempty"`
	ToAccountNumber   string                 `protobuf:"bytes,3,opt,name=to_account_number,json=toAccountNumber,proto3" json:"to_account_number,omitempty"`
	InitialAmount     string                 `protobuf:"bytes,4,opt,name=initial_amount,json=initialAmount,proto3" json:"initial_amount,omitempty"`
	FinalAmount       string                 `protobuf:"bytes,5,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	Commission        string                 `protobuf:"bytes,6,opt,name=commission,proto3" json:"commission,omitempty"`
	RecipientName     string                 `protobuf:"bytes,7,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	PaymentCode       string                 `protobuf:"bytes,8,opt,name=payment_code,json=paymentCode,proto3" json:"payment_code,omitempty"`
	ReferenceNumber   string                 `protobuf:"bytes,9,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	PaymentPurpose    string                 `protobuf:"bytes,10,opt,name=payment_purpose,json=paymentPurpose,proto3" json:"payment_purpose,omitempty"`
	Status            string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp         string                 `protobuf:"bytes,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_transaction_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentResponse) GetFromAccountNumber() string {
	if x != nil {
		return x.FromAccountNumber
	}
	return ""
}

func (x *PaymentResponse) GetToAccountNumber() string {
	if x != nil {
		return x.ToAccountNumber
	}
	return ""
}

func (x *PaymentResponse) GetInitialAmount() string {
	if x != nil {
		return x.InitialAmount
	}
	return ""
}

func (x *PaymentResponse) GetFinalAmount() string {
	if x != nil {
		return x.FinalAmount
	}
	return ""
}

func (x *PaymentResponse) GetCommission() string {
	if x != nil {
		return x.Commission
	}
	return ""
}

func (x *PaymentResponse) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *PaymentResponse) GetPaymentCode() string {
	if x != nil {
		return x.PaymentCode
	}
	return ""
}

func (x *PaymentResponse) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *PaymentResponse) GetPaymentPurpose() string {
	if x != nil {
		return x.PaymentPurpose
	}
	return ""
}

func (x *PaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type CreateTransferRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FromAccountNumber string                 `protobuf:"bytes,1,opt,name=from_account_number,json=fromAccountNumber,proto3" json:"from_account_number,omitempty"`
	ToAccountNumber   string                 `protobuf:"bytes,2,opt,name=to_account_number,json=toAccountNumber,proto3" json:"to_account_number,omitempty"`
	Amount            string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTransferRequest) GetFromAccountNumber() string {
	if x != nil {
		return x.FromAccountNumber
	}
	return ""
}

func (x *CreateTransferRequest) GetToAccountNumber() string {
	if x != nil {
		return x.ToAccountNumber
	}
	return ""
}

func (x *CreateTransferRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type GetTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferRequest) Reset() {
	*x = GetTransferRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferRequest) ProtoMessage() {}

func (x *GetTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferRequest.ProtoReflect.Descriptor instead.
func (*GetTransferRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransferRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListTransfersByClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransfersByClientRequest) Reset() {
	*x = ListTransfersByClientRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransfersByClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransfersByClientRequest) ProtoMessage() {}

func (x *ListTransfersByClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransfersByClientRequest.ProtoReflect.Descriptor instead.
func (*ListTransfersByClientRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *ListTransfersByClientRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ListTransfersByClientRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransfersByClientRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTransfersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     []*TransferResponse    `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransfersResponse) Reset() {
	*x = ListTransfersResponse{}
	mi := &file_transaction_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransfersResponse) ProtoMessage() {}

func (x *ListTransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransfersResponse.ProtoReflect.Descriptor instead.
func (*ListTransfersResponse) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *ListTransfersResponse) GetTransfers() []*TransferResponse {
	if x != nil {
		return x.Transfers
	}
	return nil
}

func (x *ListTransfersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type TransferResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromAccountNumber string                 `protobuf:"bytes,2,opt,name=from_account_number,json=fromAccountNumber,proto3" json:"from_account_number,omitempty"`
	ToAccountNumber   string                 `protobuf:"bytes,3,opt,name=to_account_number,json=toAccountNumber,proto3" json:"to_account_number,omitempty"`
	InitialAmount     string                 `protobuf:"bytes,4,opt,name=initial_amount,json=initialAmount,proto3" json:"initial_amount,omitempty"`
	FinalAmount       string                 `protobuf:"bytes,5,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	ExchangeRate      string                 `protobuf:"bytes,6,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	Commission        string                 `protobuf:"bytes,7,opt,name=commission,proto3" json:"commission,omitempty"`
	Timestamp         string                 `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_transaction_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *TransferResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransferResponse) GetFromAccountNumber() string {
	if x != nil {
		return x.FromAccountNumber
	}
	return ""
}

func (x *TransferResponse) GetToAccountNumber() string {
	if x != nil {
		return x.ToAccountNumber
	}
	return ""
}

func (x *TransferResponse) GetInitialAmount() string {
	if x != nil {
		return x.InitialAmount
	}
	return ""
}

func (x *TransferResponse) GetFinalAmount() string {
	if x != nil {
		return x.FinalAmount
	}
	return ""
}

func (x *TransferResponse) GetExchangeRate() string {
	if x != nil {
		return x.ExchangeRate
	}
	return ""
}

func (x *TransferResponse) GetCommission() string {
	if x != nil {
		return x.Commission
	}
	return ""
}

func (x *TransferResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type CreatePaymentRecipientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RecipientName string                 `protobuf:"bytes,2,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	AccountNumber string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRecipientRequest) Reset() {
	*x = CreatePaymentRecipientRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRecipientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRecipientRequest) ProtoMessage() {}

func (x *CreatePaymentRecipientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRecipientRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRecipientRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePaymentRecipientRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CreatePaymentRecipientRequest) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *CreatePaymentRecipientRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type ListPaymentRecipientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentRecipientsRequest) Reset() {
	*x = ListPaymentRecipientsRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentRecipientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentRecipientsRequest) ProtoMessage() {}

func (x *ListPaymentRecipientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentRecipientsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentRecipientsRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{11}
}

func (x *ListPaymentRecipientsRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type ListPaymentRecipientsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Recipients    []*PaymentRecipientResponse `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentRecipientsResponse) Reset() {
	*x = ListPaymentRecipientsResponse{}
	mi := &file_transaction_transaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentRecipientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentRecipientsResponse) ProtoMessage() {}

func (x *ListPaymentRecipientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentRecipientsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentRecipientsResponse) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{12}
}

func (x *ListPaymentRecipientsResponse) GetRecipients() []*PaymentRecipientResponse {
	if x != nil {
		return x.Recipients
	}
	return nil
}

type UpdatePaymentRecipientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RecipientName *string                `protobuf:"bytes,2,opt,name=recipient_name,json=recipientName,proto3,oneof" json:"recipient_name,omitempty"`
	AccountNumber *string                `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3,oneof" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentRecipientRequest) Reset() {
	*x = UpdatePaymentRecipientRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRecipientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRecipientRequest) ProtoMessage() {}

func (x *UpdatePaymentRecipientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRecipientRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRecipientRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{13}
}

func (x *UpdatePaymentRecipientRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePaymentRecipientRequest) GetRecipientName() string {
	if x != nil && x.RecipientName != nil {
		return *x.RecipientName
	}
	return ""
}

func (x *UpdatePaymentRecipientRequest) GetAccountNumber() string {
	if x != nil && x.AccountNumber != nil {
		return *x.AccountNumber
	}
	return ""
}

type DeletePaymentRecipientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePaymentRecipientRequest) Reset() {
	*x = DeletePaymentRecipientRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePaymentRecipientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentRecipientRequest) ProtoMessage() {}

func (x *DeletePaymentRecipientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentRecipientRequest.ProtoReflect.Descriptor instead.
func (*DeletePaymentRecipientRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{14}
}

func (x *DeletePaymentRecipientRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePaymentRecipientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePaymentRecipientResponse) Reset() {
	*x = DeletePaymentRecipientResponse{}
	mi := &file_transaction_transaction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePaymentRecipientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentRecipientResponse) ProtoMessage() {}

func (x *DeletePaymentRecipientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentRecipientResponse.ProtoReflect.Descriptor instead.
func (*DeletePaymentRecipientResponse) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{15}
}

func (x *DeletePaymentRecipientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PaymentRecipientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      uint64                 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RecipientName string                 `protobuf:"bytes,3,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	AccountNumber string                 `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRecipientResponse) Reset() {
	*x = PaymentRecipientResponse{}
	mi := &file_transaction_transaction_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRecipientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRecipientResponse) ProtoMessage() {}

func (x *PaymentRecipientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRecipientResponse.ProtoReflect.Descriptor instead.
func (*PaymentRecipientResponse) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{16}
}

func (x *PaymentRecipientResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentRecipientResponse) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *PaymentRecipientResponse) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *PaymentRecipientResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *PaymentRecipientResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetExchangeRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExchangeRateRequest) Reset() {
	*x = GetExchangeRateRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangeRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangeRateRequest) ProtoMessage() {}

func (x *GetExchangeRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangeRateRequest.ProtoReflect.Descriptor instead.
func (*GetExchangeRateRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{17}
}

func (x *GetExchangeRateRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *GetExchangeRateRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

type ListExchangeRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExchangeRatesRequest) Reset() {
	*x = ListExchangeRatesRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExchangeRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExchangeRatesRequest) ProtoMessage() {}

func (x *ListExchangeRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExchangeRatesRequest.ProtoReflect.Descriptor instead.
func (*ListExchangeRatesRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{18}
}

type ExchangeRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	BuyRate       string                 `protobuf:"bytes,3,opt,name=buy_rate,json=buyRate,proto3" json:"buy_rate,omitempty"`
	SellRate      string                 `protobuf:"bytes,4,opt,name=sell_rate,json=sellRate,proto3" json:"sell_rate,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRateResponse) Reset() {
	*x = ExchangeRateResponse{}
	mi := &file_transaction_transaction_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateResponse) ProtoMessage() {}

func (x *ExchangeRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateResponse.ProtoReflect.Descriptor instead.
func (*ExchangeRateResponse) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{19}
}

func (x *ExchangeRateResponse) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ExchangeRateResponse) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *ExchangeRateResponse) GetBuyRate() string {
	if x != nil {
		return x.BuyRate
	}
	return ""
}

func (x *ExchangeRateResponse) GetSellRate() string {
	if x != nil {
		return x.SellRate
	}
	return ""
}

func (x *ExchangeRateResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListExchangeRatesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Rates         []*ExchangeRateResponse `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExchangeRatesResponse) Reset() {
	*x = ListExchangeRatesResponse{}
	mi := &file_transaction_transaction_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExchangeRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExchangeRatesResponse) ProtoMessage() {}

func (x *ListExchangeRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExchangeRatesResponse.ProtoReflect.Descriptor instead.
func (*ListExchangeRatesResponse) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{20}
}

func (x *ListExchangeRatesResponse) GetRates() []*ExchangeRateResponse {
	if x != nil {
		return x.Rates
	}
	return nil
}

type CreateVerificationCodeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientId        uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	TransactionId   uint64                 `protobuf:"varint,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TransactionType string                 `protobuf:"bytes,3,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateVerificationCodeRequest) Reset() {
	*x = CreateVerificationCodeRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVerificationCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVerificationCodeRequest) ProtoMessage() {}

func (x *CreateVerificationCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVerificationCodeRequest.ProtoReflect.Descriptor instead.
func (*CreateVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{21}
}

func (x *CreateVerificationCodeRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CreateVerificationCodeRequest) GetTransactionId() uint64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *CreateVerificationCodeRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

type CreateVerificationCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVerificationCodeResponse) Reset() {
	*x = CreateVerificationCodeResponse{}
	mi := &file_transaction_transaction_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVerificationCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVerificationCodeResponse) ProtoMessage() {}

func (x *CreateVerificationCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVerificationCodeResponse.ProtoReflect.Descriptor instead.
func (*CreateVerificationCodeResponse) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{22}
}

func (x *CreateVerificationCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateVerificationCodeResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ValidateVerificationCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	TransactionId uint64                 `protobuf:"varint,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateVerificationCodeRequest) Reset() {
	*x = ValidateVerificationCodeRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateVerificationCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateVerificationCodeRequest) ProtoMessage() {}

func (x *ValidateVerificationCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateVerificationCodeRequest.ProtoReflect.Descriptor instead.
func (*ValidateVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{23}
}

func (x *ValidateVerificationCodeRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ValidateVerificationCodeRequest) GetTransactionId() uint64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *ValidateVerificationCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ValidateVerificationCodeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Valid             bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	RemainingAttempts int32                  `protobuf:"varint,2,opt,name=remaining_attempts,json=remainingAttempts,proto3" json:"remaining_attempts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ValidateVerificationCodeResponse) Reset() {
	*x = ValidateVerificationCodeResponse{}
	mi := &file_transaction_transaction_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateVerificationCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateVerificationCodeResponse) ProtoMessage() {}

func (x *ValidateVerificationCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateVerificationCodeResponse.ProtoReflect.Descriptor instead.
func (*ValidateVerificationCodeResponse) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{24}
}

func (x *ValidateVerificationCodeResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateVerificationCodeResponse) GetRemainingAttempts() int32 {
	if x != nil {
		return x.RemainingAttempts
	}
	return 0
}

var File_transaction_transaction_proto protoreflect.FileDescriptor

const file_transaction_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1dtransaction/transaction.proto\x12\vtransaction\"\xa8\x02\n" +
	"\x14CreatePaymentRequest\x12.\n" +
	"\x13from_account_number\x18\x01 \x01(\tR\x11fromAccountNumber\x12*\n" +
	"\x11to_account_number\x18\x02 \x01(\tR\x0ftoAccountNumber\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12%\n" +
	"\x0erecipient_name\x18\x04 \x01(\tR\rrecipientName\x12!\n" +
	"\fpayment_code\x18\x05 \x01(\tR\vpaymentCode\x12)\n" +
	"\x10reference_number\x18\x06 \x01(\tR\x0freferenceNumber\x12'\n" +
	"\x0fpayment_purpose\x18\a \x01(\tR\x0epaymentPurpose\"#\n" +
	"\x11GetPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x8f\x02\n" +
	"\x1cListPaymentsByAccountRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12\x1b\n" +
	"\tdate_from\x18\x02 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x03 \x01(\tR\x06dateTo\x12#\n" +
	"\rstatus_filter\x18\x04 \x01(\tR\fstatusFilter\x12\x1d\n" +
	"\n" +
	"amount_min\x18\x05 \x01(\tR\tamountMin\x12\x1d\n" +
	"\n" +
	"amount_max\x18\x06 \x01(\tR\tamountMax\x12\x12\n" +
	"\x04page\x18\a \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\b \x01(\x05R\bpageSize\"f\n" +
	"\x14ListPaymentsResponse\x128\n" +
	"\bpayments\x18\x01 \x03(\v2\x1c.transaction.PaymentResponseR\bpayments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xbb\x03\n" +
	"\x0fPaymentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12.\n" +
	"\x13from_account_number\x18\x02 \x01(\tR\x11fromAccountNumber\x12*\n" +
	"\x11to_account_number\x18\x03 \x01(\tR\x0ftoAccountNumber\x12%\n" +
	"\x0einitial_amount\x18\x04 \x01(\tR\rinitialAmount\x12!\n" +
	"\ffinal_amount\x18\x05 \x01(\tR\vfinalAmount\x12\x1e\n" +
	"\n" +
	"commission\x18\x06 \x01(\tR\n" +
	"commission\x12%\n" +
	"\x0erecipient_name\x18\a \x01(\tR\rrecipientName\x12!\n" +
	"\fpayment_code\x18\b \x01(\tR\vpaymentCode\x12)\n" +
	"\x10reference_number\x18\t \x01(\tR\x0freferenceNumber\x12'\n" +
	"\x0fpayment_purpose\x18\n" +
	" \x01(\tR\x0epaymentPurpose\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\f \x01(\tR\ttimestamp\"\x8b\x01\n" +
	"\x15CreateTransferRequest\x12.\n" +
	"\x13from_account_number\x18\x01 \x01(\tR\x11fromAccountNumber\x12*\n" +
	"\x11to_account_number\x18\x02 \x01(\tR\x0ftoAccountNumber\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"$\n" +
	"\x12GetTransferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"l\n" +
	"\x1cListTransfersByClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"j\n" +
	"\x15ListTransfersResponse\x12;\n" +
	"\ttransfers\x18\x01 \x03(\v2\x1d.transaction.TransferResponseR\ttransfers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xab\x02\n" +
	"\x10TransferResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12.\n" +
	"\x13from_account_number\x18\x02 \x01(\tR\x11fromAccountNumber\x12*\n" +
	"\x11to_account_number\x18\x03 \x01(\tR\x0ftoAccountNumber\x12%\n" +
	"\x0einitial_amount\x18\x04 \x01(\tR\rinitialAmount\x12!\n" +
	"\ffinal_amount\x18\x05 \x01(\tR\vfinalAmount\x12#\n" +
	"\rexchange_rate\x18\x06 \x01(\tR\fexchangeRate\x12\x1e\n" +
	"\n" +
	"commission\x18\a \x01(\tR\n" +
	"commission\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\tR\ttimestamp\"\x8a\x01\n" +
	"\x1dCreatePaymentRecipientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12%\n" +
	"\x0erecipient_name\x18\x02 \x01(\tR\rrecipientName\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\";\n" +
	"\x1cListPaymentRecipientsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\"f\n" +
	"\x1dListPaymentRecipientsResponse\x12E\n" +
	"\n" +
	"recipients\x18\x01 \x03(\v2%.transaction.PaymentRecipientResponseR\n" +
	"recipients\"\xad\x01\n" +
	"\x1dUpdatePaymentRecipientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12*\n" +
	"\x0erecipient_name\x18\x02 \x01(\tH\x00R\rrecipientName\x88\x01\x01\x12*\n" +
	"\x0eaccount_number\x18\x03 \x01(\tH\x01R\raccountNumber\x88\x01\x01B\x11\n" +
	"\x0f_recipient_nameB\x11\n" +
	"\x0f_account_number\"/\n" +
	"\x1dDeletePaymentRecipientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\":\n" +
	"\x1eDeletePaymentRecipientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb4\x01\n" +
	"\x18PaymentRecipientResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x04R\bclientId\x12%\n" +
	"\x0erecipient_name\x18\x03 \x01(\tR\rrecipientName\x12%\n" +
	"\x0eaccount_number\x18\x04 \x01(\tR\raccountNumber\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"^\n" +
	"\x16GetExchangeRateRequest\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\"\x1a\n" +
	"\x18ListExchangeRatesRequest\"\xb3\x01\n" +
	"\x14ExchangeRateResponse\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\x12\x19\n" +
	"\bbuy_rate\x18\x03 \x01(\tR\abuyRate\x12\x1b\n" +
	"\tsell_rate\x18\x04 \x01(\tR\bsellRate\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"T\n" +
	"\x19ListExchangeRatesResponse\x127\n" +
	"\x05rates\x18\x01 \x03(\v2!.transaction.ExchangeRateResponseR\x05rates\"\x8e\x01\n" +
	"\x1dCreateVerificationCodeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\x04R\rtransactionId\x12)\n" +
	"\x10transaction_type\x18\x03 \x01(\tR\x0ftransactionType\"S\n" +
	"\x1eCreateVerificationCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"y\n" +
	"\x1fValidateVerificationCodeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\x04R\rtransactionId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"g\n" +
	" ValidateVerificationCodeResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12-\n" +
	"\x12remaining_attempts\x18\x02 \x01(\x05R\x11remainingAttempts2\x8d\v\n" +
	"\x12TransactionService\x12P\n" +
	"\rCreatePayment\x12!.transaction.CreatePaymentRequest\x1a\x1c.transaction.PaymentResponse\x12J\n" +
	"\n" +
	"GetPayment\x12\x1e.transaction.GetPaymentRequest\x1a\x1c.transaction.PaymentResponse\x12e\n" +
	"\x15ListPaymentsByAccount\x12).transaction.ListPaymentsByAccountRequest\x1a!.transaction.ListPaymentsResponse\x12S\n" +
	"\x0eCreateTransfer\x12\".transaction.CreateTransferRequest\x1a\x1d.transaction.TransferResponse\x12M\n" +
	"\vGetTransfer\x12\x1f.transaction.GetTransferRequest\x1a\x1d.transaction.TransferResponse\x12f\n" +
	"\x15ListTransfersByClient\x12).transaction.ListTransfersByClientRequest\x1a\".transaction.ListTransfersResponse\x12k\n" +
	"\x16CreatePaymentRecipient\x12*.transaction.CreatePaymentRecipientRequest\x1a%.transaction.PaymentRecipientResponse\x12n\n" +
	"\x15ListPaymentRecipients\x12).transaction.ListPaymentRecipientsRequest\x1a*.transaction.ListPaymentRecipientsResponse\x12k\n" +
	"\x16UpdatePaymentRecipient\x12*.transaction.UpdatePaymentRecipientRequest\x1a%.transaction.PaymentRecipientResponse\x12q\n" +
	"\x16DeletePaymentRecipient\x12*.transaction.DeletePaymentRecipientRequest\x1a+.transaction.DeletePaymentRecipientResponse\x12Y\n" +
	"\x0fGetExchangeRate\x12#.transaction.GetExchangeRateRequest\x1a!.transaction.ExchangeRateResponse\x12b\n" +
	"\x11ListExchangeRates\x12%.transaction.ListExchangeRatesRequest\x1a&.transaction.ListExchangeRatesResponse\x12q\n" +
	"\x16CreateVerificationCode\x12*.transaction.CreateVerificationCodeRequest\x1a+.transaction.CreateVerificationCodeResponse\x12w\n" +
	"\x18ValidateVerificationCode\x12,.transaction.ValidateVerificationCodeRequest\x1a-.transaction.ValidateVerificationCodeResponseB9Z7github.com/exbanka/contract/transactionpb;transactionpbb\x06proto3"

var (
	file_transaction_transaction_proto_rawDescOnce sync.Once
	file_transaction_transaction_proto_rawDescData []byte
)

func file_transaction_transaction_proto_rawDescGZIP() []byte {
	file_transaction_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_transaction_proto_rawDesc), len(file_transaction_transaction_proto_rawDesc)))
	})
	return file_transaction_transaction_proto_rawDescData
}

var file_transaction_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_transaction_transaction_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil),             // 0: transaction.CreatePaymentRequest
	(*GetPaymentRequest)(nil),                // 1: transaction.GetPaymentRequest
	(*ListPaymentsByAccountRequest)(nil),     // 2: transaction.ListPaymentsByAccountRequest
	(*ListPaymentsResponse)(nil),             // 3: transaction.ListPaymentsResponse
	(*PaymentResponse)(nil),                  // 4: transaction.PaymentResponse
	(*CreateTransferRequest)(nil),            // 5: transaction.CreateTransferRequest
	(*GetTransferRequest)(nil),               // 6: transaction.GetTransferRequest
	(*ListTransfersByClientRequest)(nil),     // 7: transaction.ListTransfersByClientRequest
	(*ListTransfersResponse)(nil),            // 8: transaction.ListTransfersResponse
	(*TransferResponse)(nil),                 // 9: transaction.TransferResponse
	(*CreatePaymentRecipientRequest)(nil),    // 10: transaction.CreatePaymentRecipientRequest
	(*ListPaymentRecipientsRequest)(nil),     // 11: transaction.ListPaymentRecipientsRequest
	(*ListPaymentRecipientsResponse)(nil),    // 12: transaction.ListPaymentRecipientsResponse
	(*UpdatePaymentRecipientRequest)(nil),    // 13: transaction.UpdatePaymentRecipientRequest
	(*DeletePaymentRecipientRequest)(nil),    // 14: transaction.DeletePaymentRecipientRequest
	(*DeletePaymentRecipientResponse)(nil),   // 15: transaction.DeletePaymentRecipientResponse
	(*PaymentRecipientResponse)(nil),         // 16: transaction.PaymentRecipientResponse
	(*GetExchangeRateRequest)(nil),           // 17: transaction.GetExchangeRateRequest
	(*ListExchangeRatesRequest)(nil),         // 18: transaction.ListExchangeRatesRequest
	(*ExchangeRateResponse)(nil),             // 19: transaction.ExchangeRateResponse
	(*ListExchangeRatesResponse)(nil),        // 20: transaction.ListExchangeRatesResponse
	(*CreateVerificationCodeRequest)(nil),    // 21: transaction.CreateVerificationCodeRequest
	(*CreateVerificationCodeResponse)(nil),   // 22: transaction.CreateVerificationCodeResponse
	(*ValidateVerificationCodeRequest)(nil),  // 23: transaction.ValidateVerificationCodeRequest
	(*ValidateVerificationCodeResponse)(nil), // 24: transaction.ValidateVerificationCodeResponse
}
var file_transaction_transaction_proto_depIdxs = []int32{
	4,  // 0: transaction.ListPaymentsResponse.payments:type_name -> transaction.PaymentResponse
	9,  // 1: transaction.ListTransfersResponse.transfers:type_name -> transaction.TransferResponse
	16, // 2: transaction.ListPaymentRecipientsResponse.recipients:type_name -> transaction.PaymentRecipientResponse
	19, // 3: transaction.ListExchangeRatesResponse.rates:type_name -> transaction.ExchangeRateResponse
	0,  // 4: transaction.TransactionService.CreatePayment:input_type -> transaction.CreatePaymentRequest
	1,  // 5: transaction.TransactionService.GetPayment:input_type -> transaction.GetPaymentRequest
	2,  // 6: transaction.TransactionService.ListPaymentsByAccount:input_type -> transaction.ListPaymentsByAccountRequest
	5,  // 7: transaction.TransactionService.CreateTransfer:input_type -> transaction.CreateTransferRequest
	6,  // 8: transaction.TransactionService.GetTransfer:input_type -> transaction.GetTransferRequest
	7,  // 9: transaction.TransactionService.ListTransfersByClient:input_type -> transaction.ListTransfersByClientRequest
	10, // 10: transaction.TransactionService.CreatePaymentRecipient:input_type -> transaction.CreatePaymentRecipientRequest
	11, // 11: transaction.TransactionService.ListPaymentRecipients:input_type -> transaction.ListPaymentRecipientsRequest
	13, // 12: transaction.TransactionService.UpdatePaymentRecipient:input_type -> transaction.UpdatePaymentRecipientRequest
	14, // 13: transaction.TransactionService.DeletePaymentRecipient:input_type -> transaction.DeletePaymentRecipientRequest
	17, // 14: transaction.TransactionService.GetExchangeRate:input_type -> transaction.GetExchangeRateRequest
	18, // 15: transaction.TransactionService.ListExchangeRates:input_type -> transaction.ListExchangeRatesRequest
	21, // 16: transaction.TransactionService.CreateVerificationCode:input_type -> transaction.CreateVerificationCodeRequest
	23, // 17: transaction.TransactionService.ValidateVerificationCode:input_type -> transaction.ValidateVerificationCodeRequest
	4,  // 18: transaction.TransactionService.CreatePayment:output_type -> transaction.PaymentResponse
	4,  // 19: transaction.TransactionService.GetPayment:output_type -> transaction.PaymentResponse
	3,  // 20: transaction.TransactionService.ListPaymentsByAccount:output_type -> transaction.ListPaymentsResponse
	9,  // 21: transaction.TransactionService.CreateTransfer:output_type -> transaction.TransferResponse
	9,  // 22: transaction.TransactionService.GetTransfer:output_type -> transaction.TransferResponse
	8,  // 23: transaction.TransactionService.ListTransfersByClient:output_type -> transaction.ListTransfersResponse
	16, // 24: transaction.TransactionService.CreatePaymentRecipient:output_type -> transaction.PaymentRecipientResponse
	12, // 25: transaction.TransactionService.ListPaymentRecipients:output_type -> transaction.ListPaymentRecipientsResponse
	16, // 26: transaction.TransactionService.UpdatePaymentRecipient:output_type -> transaction.PaymentRecipientResponse
	15, // 27: transaction.TransactionService.DeletePaymentRecipient:output_type -> transaction.DeletePaymentRecipientResponse
	19, // 28: transaction.TransactionService.GetExchangeRate:output_type -> transaction.ExchangeRateResponse
	20, // 29: transaction.TransactionService.ListExchangeRates:output_type -> transaction.ListExchangeRatesResponse
	22, // 30: transaction.TransactionService.CreateVerificationCode:output_type -> transaction.CreateVerificationCodeResponse
	24, // 31: transaction.TransactionService.ValidateVerificationCode:output_type -> transaction.ValidateVerificationCodeResponse
	18, // [18:32] is the sub-list for method output_type
	4,  // [4:18] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_transaction_transaction_proto_init() }
func file_transaction_transaction_proto_init() {
	if File_transaction_transaction_proto != nil {
		return
	}
	file_transaction_transaction_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_transaction_proto_rawDesc), len(file_transaction_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_transaction_proto_msgTypes,
	}.Build()
	File_transaction_transaction_proto = out.File
	file_transaction_transaction_proto_goTypes = nil
	file_transaction_transaction_proto_depIdxs = nil
}
