// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: verification/verification.proto

package verificationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VerificationGRPCService_CreateChallenge_FullMethodName     = "/verification.VerificationGRPCService/CreateChallenge"
	VerificationGRPCService_GetChallengeStatus_FullMethodName  = "/verification.VerificationGRPCService/GetChallengeStatus"
	VerificationGRPCService_GetPendingChallenge_FullMethodName = "/verification.VerificationGRPCService/GetPendingChallenge"
	VerificationGRPCService_SubmitVerification_FullMethodName  = "/verification.VerificationGRPCService/SubmitVerification"
	VerificationGRPCService_SubmitCode_FullMethodName          = "/verification.VerificationGRPCService/SubmitCode"
	VerificationGRPCService_VerifyByBiometric_FullMethodName   = "/verification.VerificationGRPCService/VerifyByBiometric"
)

// VerificationGRPCServiceClient is the client API for VerificationGRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerificationGRPCServiceClient interface {
	// CreateChallenge creates a new verification challenge for a transaction.
	CreateChallenge(ctx context.Context, in *CreateChallengeRequest, opts ...grpc.CallOption) (*CreateChallengeResponse, error)
	// GetChallengeStatus returns the current status of a verification challenge.
	GetChallengeStatus(ctx context.Context, in *GetChallengeStatusRequest, opts ...grpc.CallOption) (*GetChallengeStatusResponse, error)
	// GetPendingChallenge returns the pending challenge for a user+device (mobile polling).
	GetPendingChallenge(ctx context.Context, in *GetPendingChallengeRequest, opts ...grpc.CallOption) (*GetPendingChallengeResponse, error)
	// SubmitVerification validates a mobile-submitted response (qr_scan, number_match, code_pull with biometric).
	SubmitVerification(ctx context.Context, in *SubmitVerificationRequest, opts ...grpc.CallOption) (*SubmitVerificationResponse, error)
	// SubmitCode validates a browser-submitted 6-digit code (code_pull, email fallback).
	SubmitCode(ctx context.Context, in *SubmitCodeRequest, opts ...grpc.CallOption) (*SubmitCodeResponse, error)
	// VerifyByBiometric verifies a challenge using device biometrics (device signature is the proof).
	VerifyByBiometric(ctx context.Context, in *VerifyByBiometricRequest, opts ...grpc.CallOption) (*VerifyByBiometricResponse, error)
}

type verificationGRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVerificationGRPCServiceClient(cc grpc.ClientConnInterface) VerificationGRPCServiceClient {
	return &verificationGRPCServiceClient{cc}
}

func (c *verificationGRPCServiceClient) CreateChallenge(ctx context.Context, in *CreateChallengeRequest, opts ...grpc.CallOption) (*CreateChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChallengeResponse)
	err := c.cc.Invoke(ctx, VerificationGRPCService_CreateChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verificationGRPCServiceClient) GetChallengeStatus(ctx context.Context, in *GetChallengeStatusRequest, opts ...grpc.CallOption) (*GetChallengeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChallengeStatusResponse)
	err := c.cc.Invoke(ctx, VerificationGRPCService_GetChallengeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verificationGRPCServiceClient) GetPendingChallenge(ctx context.Context, in *GetPendingChallengeRequest, opts ...grpc.CallOption) (*GetPendingChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPendingChallengeResponse)
	err := c.cc.Invoke(ctx, VerificationGRPCService_GetPendingChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verificationGRPCServiceClient) SubmitVerification(ctx context.Context, in *SubmitVerificationRequest, opts ...grpc.CallOption) (*SubmitVerificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitVerificationResponse)
	err := c.cc.Invoke(ctx, VerificationGRPCService_SubmitVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verificationGRPCServiceClient) SubmitCode(ctx context.Context, in *SubmitCodeRequest, opts ...grpc.CallOption) (*SubmitCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitCodeResponse)
	err := c.cc.Invoke(ctx, VerificationGRPCService_SubmitCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verificationGRPCServiceClient) VerifyByBiometric(ctx context.Context, in *VerifyByBiometricRequest, opts ...grpc.CallOption) (*VerifyByBiometricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyByBiometricResponse)
	err := c.cc.Invoke(ctx, VerificationGRPCService_VerifyByBiometric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerificationGRPCServiceServer is the server API for VerificationGRPCService service.
// All implementations must embed UnimplementedVerificationGRPCServiceServer
// for forward compatibility.
type VerificationGRPCServiceServer interface {
	// CreateChallenge creates a new verification challenge for a transaction.
	CreateChallenge(context.Context, *CreateChallengeRequest) (*CreateChallengeResponse, error)
	// GetChallengeStatus returns the current status of a verification challenge.
	GetChallengeStatus(context.Context, *GetChallengeStatusRequest) (*GetChallengeStatusResponse, error)
	// GetPendingChallenge returns the pending challenge for a user+device (mobile polling).
	GetPendingChallenge(context.Context, *GetPendingChallengeRequest) (*GetPendingChallengeResponse, error)
	// SubmitVerification validates a mobile-submitted response (qr_scan, number_match, code_pull with biometric).
	SubmitVerification(context.Context, *SubmitVerificationRequest) (*SubmitVerificationResponse, error)
	// SubmitCode validates a browser-submitted 6-digit code (code_pull, email fallback).
	SubmitCode(context.Context, *SubmitCodeRequest) (*SubmitCodeResponse, error)
	// VerifyByBiometric verifies a challenge using device biometrics (device signature is the proof).
	VerifyByBiometric(context.Context, *VerifyByBiometricRequest) (*VerifyByBiometricResponse, error)
	mustEmbedUnimplementedVerificationGRPCServiceServer()
}

// UnimplementedVerificationGRPCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVerificationGRPCServiceServer struct{}

func (UnimplementedVerificationGRPCServiceServer) CreateChallenge(context.Context, *CreateChallengeRequest) (*CreateChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChallenge not implemented")
}
func (UnimplementedVerificationGRPCServiceServer) GetChallengeStatus(context.Context, *GetChallengeStatusRequest) (*GetChallengeStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChallengeStatus not implemented")
}
func (UnimplementedVerificationGRPCServiceServer) GetPendingChallenge(context.Context, *GetPendingChallengeRequest) (*GetPendingChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingChallenge not implemented")
}
func (UnimplementedVerificationGRPCServiceServer) SubmitVerification(context.Context, *SubmitVerificationRequest) (*SubmitVerificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitVerification not implemented")
}
func (UnimplementedVerificationGRPCServiceServer) SubmitCode(context.Context, *SubmitCodeRequest) (*SubmitCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitCode not implemented")
}
func (UnimplementedVerificationGRPCServiceServer) VerifyByBiometric(context.Context, *VerifyByBiometricRequest) (*VerifyByBiometricResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyByBiometric not implemented")
}
func (UnimplementedVerificationGRPCServiceServer) mustEmbedUnimplementedVerificationGRPCServiceServer() {
}
func (UnimplementedVerificationGRPCServiceServer) testEmbeddedByValue() {}

// UnsafeVerificationGRPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerificationGRPCServiceServer will
// result in compilation errors.
type UnsafeVerificationGRPCServiceServer interface {
	mustEmbedUnimplementedVerificationGRPCServiceServer()
}

func RegisterVerificationGRPCServiceServer(s grpc.ServiceRegistrar, srv VerificationGRPCServiceServer) {
	// If the following call panics, it indicates UnimplementedVerificationGRPCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VerificationGRPCService_ServiceDesc, srv)
}

func _VerificationGRPCService_CreateChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationGRPCServiceServer).CreateChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerificationGRPCService_CreateChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationGRPCServiceServer).CreateChallenge(ctx, req.(*CreateChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerificationGRPCService_GetChallengeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChallengeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationGRPCServiceServer).GetChallengeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerificationGRPCService_GetChallengeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationGRPCServiceServer).GetChallengeStatus(ctx, req.(*GetChallengeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerificationGRPCService_GetPendingChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationGRPCServiceServer).GetPendingChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerificationGRPCService_GetPendingChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationGRPCServiceServer).GetPendingChallenge(ctx, req.(*GetPendingChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerificationGRPCService_SubmitVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationGRPCServiceServer).SubmitVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerificationGRPCService_SubmitVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationGRPCServiceServer).SubmitVerification(ctx, req.(*SubmitVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerificationGRPCService_SubmitCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationGRPCServiceServer).SubmitCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerificationGRPCService_SubmitCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationGRPCServiceServer).SubmitCode(ctx, req.(*SubmitCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerificationGRPCService_VerifyByBiometric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyByBiometricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationGRPCServiceServer).VerifyByBiometric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerificationGRPCService_VerifyByBiometric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationGRPCServiceServer).VerifyByBiometric(ctx, req.(*VerifyByBiometricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VerificationGRPCService_ServiceDesc is the grpc.ServiceDesc for VerificationGRPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerificationGRPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "verification.VerificationGRPCService",
	HandlerType: (*VerificationGRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChallenge",
			Handler:    _VerificationGRPCService_CreateChallenge_Handler,
		},
		{
			MethodName: "GetChallengeStatus",
			Handler:    _VerificationGRPCService_GetChallengeStatus_Handler,
		},
		{
			MethodName: "GetPendingChallenge",
			Handler:    _VerificationGRPCService_GetPendingChallenge_Handler,
		},
		{
			MethodName: "SubmitVerification",
			Handler:    _VerificationGRPCService_SubmitVerification_Handler,
		},
		{
			MethodName: "SubmitCode",
			Handler:    _VerificationGRPCService_SubmitCode_Handler,
		},
		{
			MethodName: "VerifyByBiometric",
			Handler:    _VerificationGRPCService_VerifyByBiometric_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verification/verification.proto",
}
