// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: credit/credit.proto

package creditpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CreditService_CreateLoanRequest_FullMethodName     = "/credit.CreditService/CreateLoanRequest"
	CreditService_GetLoanRequest_FullMethodName        = "/credit.CreditService/GetLoanRequest"
	CreditService_ListLoanRequests_FullMethodName      = "/credit.CreditService/ListLoanRequests"
	CreditService_ApproveLoanRequest_FullMethodName    = "/credit.CreditService/ApproveLoanRequest"
	CreditService_RejectLoanRequest_FullMethodName     = "/credit.CreditService/RejectLoanRequest"
	CreditService_GetLoan_FullMethodName               = "/credit.CreditService/GetLoan"
	CreditService_ListLoansByClient_FullMethodName     = "/credit.CreditService/ListLoansByClient"
	CreditService_ListAllLoans_FullMethodName          = "/credit.CreditService/ListAllLoans"
	CreditService_GetInstallmentsByLoan_FullMethodName = "/credit.CreditService/GetInstallmentsByLoan"
)

// CreditServiceClient is the client API for CreditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreditServiceClient interface {
	CreateLoanRequest(ctx context.Context, in *CreateLoanRequestReq, opts ...grpc.CallOption) (*LoanRequestResponse, error)
	GetLoanRequest(ctx context.Context, in *GetLoanRequestReq, opts ...grpc.CallOption) (*LoanRequestResponse, error)
	ListLoanRequests(ctx context.Context, in *ListLoanRequestsReq, opts ...grpc.CallOption) (*ListLoanRequestsResponse, error)
	ApproveLoanRequest(ctx context.Context, in *ApproveLoanRequestReq, opts ...grpc.CallOption) (*LoanResponse, error)
	RejectLoanRequest(ctx context.Context, in *RejectLoanRequestReq, opts ...grpc.CallOption) (*LoanRequestResponse, error)
	GetLoan(ctx context.Context, in *GetLoanReq, opts ...grpc.CallOption) (*LoanResponse, error)
	ListLoansByClient(ctx context.Context, in *ListLoansByClientReq, opts ...grpc.CallOption) (*ListLoansResponse, error)
	ListAllLoans(ctx context.Context, in *ListAllLoansReq, opts ...grpc.CallOption) (*ListLoansResponse, error)
	GetInstallmentsByLoan(ctx context.Context, in *GetInstallmentsByLoanReq, opts ...grpc.CallOption) (*ListInstallmentsResponse, error)
}

type creditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCreditServiceClient(cc grpc.ClientConnInterface) CreditServiceClient {
	return &creditServiceClient{cc}
}

func (c *creditServiceClient) CreateLoanRequest(ctx context.Context, in *CreateLoanRequestReq, opts ...grpc.CallOption) (*LoanRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoanRequestResponse)
	err := c.cc.Invoke(ctx, CreditService_CreateLoanRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) GetLoanRequest(ctx context.Context, in *GetLoanRequestReq, opts ...grpc.CallOption) (*LoanRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoanRequestResponse)
	err := c.cc.Invoke(ctx, CreditService_GetLoanRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) ListLoanRequests(ctx context.Context, in *ListLoanRequestsReq, opts ...grpc.CallOption) (*ListLoanRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLoanRequestsResponse)
	err := c.cc.Invoke(ctx, CreditService_ListLoanRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) ApproveLoanRequest(ctx context.Context, in *ApproveLoanRequestReq, opts ...grpc.CallOption) (*LoanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoanResponse)
	err := c.cc.Invoke(ctx, CreditService_ApproveLoanRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) RejectLoanRequest(ctx context.Context, in *RejectLoanRequestReq, opts ...grpc.CallOption) (*LoanRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoanRequestResponse)
	err := c.cc.Invoke(ctx, CreditService_RejectLoanRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) GetLoan(ctx context.Context, in *GetLoanReq, opts ...grpc.CallOption) (*LoanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoanResponse)
	err := c.cc.Invoke(ctx, CreditService_GetLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) ListLoansByClient(ctx context.Context, in *ListLoansByClientReq, opts ...grpc.CallOption) (*ListLoansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLoansResponse)
	err := c.cc.Invoke(ctx, CreditService_ListLoansByClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) ListAllLoans(ctx context.Context, in *ListAllLoansReq, opts ...grpc.CallOption) (*ListLoansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLoansResponse)
	err := c.cc.Invoke(ctx, CreditService_ListAllLoans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) GetInstallmentsByLoan(ctx context.Context, in *GetInstallmentsByLoanReq, opts ...grpc.CallOption) (*ListInstallmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstallmentsResponse)
	err := c.cc.Invoke(ctx, CreditService_GetInstallmentsByLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreditServiceServer is the server API for CreditService service.
// All implementations must embed UnimplementedCreditServiceServer
// for forward compatibility.
type CreditServiceServer interface {
	CreateLoanRequest(context.Context, *CreateLoanRequestReq) (*LoanRequestResponse, error)
	GetLoanRequest(context.Context, *GetLoanRequestReq) (*LoanRequestResponse, error)
	ListLoanRequests(context.Context, *ListLoanRequestsReq) (*ListLoanRequestsResponse, error)
	ApproveLoanRequest(context.Context, *ApproveLoanRequestReq) (*LoanResponse, error)
	RejectLoanRequest(context.Context, *RejectLoanRequestReq) (*LoanRequestResponse, error)
	GetLoan(context.Context, *GetLoanReq) (*LoanResponse, error)
	ListLoansByClient(context.Context, *ListLoansByClientReq) (*ListLoansResponse, error)
	ListAllLoans(context.Context, *ListAllLoansReq) (*ListLoansResponse, error)
	GetInstallmentsByLoan(context.Context, *GetInstallmentsByLoanReq) (*ListInstallmentsResponse, error)
	mustEmbedUnimplementedCreditServiceServer()
}

// UnimplementedCreditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCreditServiceServer struct{}

func (UnimplementedCreditServiceServer) CreateLoanRequest(context.Context, *CreateLoanRequestReq) (*LoanRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLoanRequest not implemented")
}
func (UnimplementedCreditServiceServer) GetLoanRequest(context.Context, *GetLoanRequestReq) (*LoanRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoanRequest not implemented")
}
func (UnimplementedCreditServiceServer) ListLoanRequests(context.Context, *ListLoanRequestsReq) (*ListLoanRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLoanRequests not implemented")
}
func (UnimplementedCreditServiceServer) ApproveLoanRequest(context.Context, *ApproveLoanRequestReq) (*LoanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveLoanRequest not implemented")
}
func (UnimplementedCreditServiceServer) RejectLoanRequest(context.Context, *RejectLoanRequestReq) (*LoanRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectLoanRequest not implemented")
}
func (UnimplementedCreditServiceServer) GetLoan(context.Context, *GetLoanReq) (*LoanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoan not implemented")
}
func (UnimplementedCreditServiceServer) ListLoansByClient(context.Context, *ListLoansByClientReq) (*ListLoansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLoansByClient not implemented")
}
func (UnimplementedCreditServiceServer) ListAllLoans(context.Context, *ListAllLoansReq) (*ListLoansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllLoans not implemented")
}
func (UnimplementedCreditServiceServer) GetInstallmentsByLoan(context.Context, *GetInstallmentsByLoanReq) (*ListInstallmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstallmentsByLoan not implemented")
}
func (UnimplementedCreditServiceServer) mustEmbedUnimplementedCreditServiceServer() {}
func (UnimplementedCreditServiceServer) testEmbeddedByValue()                       {}

// UnsafeCreditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreditServiceServer will
// result in compilation errors.
type UnsafeCreditServiceServer interface {
	mustEmbedUnimplementedCreditServiceServer()
}

func RegisterCreditServiceServer(s grpc.ServiceRegistrar, srv CreditServiceServer) {
	// If the following call panics, it indicates UnimplementedCreditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CreditService_ServiceDesc, srv)
}

func _CreditService_CreateLoanRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoanRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).CreateLoanRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_CreateLoanRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).CreateLoanRequest(ctx, req.(*CreateLoanRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_GetLoanRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoanRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).GetLoanRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_GetLoanRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).GetLoanRequest(ctx, req.(*GetLoanRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_ListLoanRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLoanRequestsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).ListLoanRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_ListLoanRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).ListLoanRequests(ctx, req.(*ListLoanRequestsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_ApproveLoanRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveLoanRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).ApproveLoanRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_ApproveLoanRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).ApproveLoanRequest(ctx, req.(*ApproveLoanRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_RejectLoanRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectLoanRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).RejectLoanRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_RejectLoanRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).RejectLoanRequest(ctx, req.(*RejectLoanRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_GetLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).GetLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_GetLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).GetLoan(ctx, req.(*GetLoanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_ListLoansByClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLoansByClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).ListLoansByClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_ListLoansByClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).ListLoansByClient(ctx, req.(*ListLoansByClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_ListAllLoans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllLoansReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).ListAllLoans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_ListAllLoans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).ListAllLoans(ctx, req.(*ListAllLoansReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_GetInstallmentsByLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstallmentsByLoanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).GetInstallmentsByLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_GetInstallmentsByLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).GetInstallmentsByLoan(ctx, req.(*GetInstallmentsByLoanReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CreditService_ServiceDesc is the grpc.ServiceDesc for CreditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "credit.CreditService",
	HandlerType: (*CreditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLoanRequest",
			Handler:    _CreditService_CreateLoanRequest_Handler,
		},
		{
			MethodName: "GetLoanRequest",
			Handler:    _CreditService_GetLoanRequest_Handler,
		},
		{
			MethodName: "ListLoanRequests",
			Handler:    _CreditService_ListLoanRequests_Handler,
		},
		{
			MethodName: "ApproveLoanRequest",
			Handler:    _CreditService_ApproveLoanRequest_Handler,
		},
		{
			MethodName: "RejectLoanRequest",
			Handler:    _CreditService_RejectLoanRequest_Handler,
		},
		{
			MethodName: "GetLoan",
			Handler:    _CreditService_GetLoan_Handler,
		},
		{
			MethodName: "ListLoansByClient",
			Handler:    _CreditService_ListLoansByClient_Handler,
		},
		{
			MethodName: "ListAllLoans",
			Handler:    _CreditService_ListAllLoans_Handler,
		},
		{
			MethodName: "GetInstallmentsByLoan",
			Handler:    _CreditService_GetInstallmentsByLoan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "credit/credit.proto",
}
