// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: credit/credit.proto

package creditpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLoanRequestReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClientId         uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	LoanType         string                 `protobuf:"bytes,2,opt,name=loan_type,json=loanType,proto3" json:"loan_type,omitempty"`
	InterestType     string                 `protobuf:"bytes,3,opt,name=interest_type,json=interestType,proto3" json:"interest_type,omitempty"`
	Amount           string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CurrencyCode     string                 `protobuf:"bytes,5,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Purpose          string                 `protobuf:"bytes,6,opt,name=purpose,proto3" json:"purpose,omitempty"`
	MonthlySalary    string                 `protobuf:"bytes,7,opt,name=monthly_salary,json=monthlySalary,proto3" json:"monthly_salary,omitempty"`
	EmploymentStatus string                 `protobuf:"bytes,8,opt,name=employment_status,json=employmentStatus,proto3" json:"employment_status,omitempty"`
	EmploymentPeriod int32                  `protobuf:"varint,9,opt,name=employment_period,json=employmentPeriod,proto3" json:"employment_period,omitempty"`
	RepaymentPeriod  int32                  `protobuf:"varint,10,opt,name=repayment_period,json=repaymentPeriod,proto3" json:"repayment_period,omitempty"`
	Phone            string                 `protobuf:"bytes,11,opt,name=phone,proto3" json:"phone,omitempty"`
	AccountNumber    string                 `protobuf:"bytes,12,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateLoanRequestReq) Reset() {
	*x = CreateLoanRequestReq{}
	mi := &file_credit_credit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanRequestReq) ProtoMessage() {}

func (x *CreateLoanRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanRequestReq.ProtoReflect.Descriptor instead.
func (*CreateLoanRequestReq) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLoanRequestReq) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CreateLoanRequestReq) GetLoanType() string {
	if x != nil {
		return x.LoanType
	}
	return ""
}

func (x *CreateLoanRequestReq) GetInterestType() string {
	if x != nil {
		return x.InterestType
	}
	return ""
}

func (x *CreateLoanRequestReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateLoanRequestReq) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *CreateLoanRequestReq) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *CreateLoanRequestReq) GetMonthlySalary() string {
	if x != nil {
		return x.MonthlySalary
	}
	return ""
}

func (x *CreateLoanRequestReq) GetEmploymentStatus() string {
	if x != nil {
		return x.EmploymentStatus
	}
	return ""
}

func (x *CreateLoanRequestReq) GetEmploymentPeriod() int32 {
	if x != nil {
		return x.EmploymentPeriod
	}
	return 0
}

func (x *CreateLoanRequestReq) GetRepaymentPeriod() int32 {
	if x != nil {
		return x.RepaymentPeriod
	}
	return 0
}

func (x *CreateLoanRequestReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateLoanRequestReq) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type GetLoanRequestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanRequestReq) Reset() {
	*x = GetLoanRequestReq{}
	mi := &file_credit_credit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanRequestReq) ProtoMessage() {}

func (x *GetLoanRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanRequestReq.ProtoReflect.Descriptor instead.
func (*GetLoanRequestReq) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{1}
}

func (x *GetLoanRequestReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListLoanRequestsReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LoanTypeFilter      string                 `protobuf:"bytes,1,opt,name=loan_type_filter,json=loanTypeFilter,proto3" json:"loan_type_filter,omitempty"`
	AccountNumberFilter string                 `protobuf:"bytes,2,opt,name=account_number_filter,json=accountNumberFilter,proto3" json:"account_number_filter,omitempty"`
	StatusFilter        string                 `protobuf:"bytes,3,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	Page                int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize            int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ClientIdFilter      uint64                 `protobuf:"varint,6,opt,name=client_id_filter,json=clientIdFilter,proto3" json:"client_id_filter,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListLoanRequestsReq) Reset() {
	*x = ListLoanRequestsReq{}
	mi := &file_credit_credit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoanRequestsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoanRequestsReq) ProtoMessage() {}

func (x *ListLoanRequestsReq) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoanRequestsReq.ProtoReflect.Descriptor instead.
func (*ListLoanRequestsReq) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{2}
}

func (x *ListLoanRequestsReq) GetLoanTypeFilter() string {
	if x != nil {
		return x.LoanTypeFilter
	}
	return ""
}

func (x *ListLoanRequestsReq) GetAccountNumberFilter() string {
	if x != nil {
		return x.AccountNumberFilter
	}
	return ""
}

func (x *ListLoanRequestsReq) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

func (x *ListLoanRequestsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLoanRequestsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLoanRequestsReq) GetClientIdFilter() uint64 {
	if x != nil {
		return x.ClientIdFilter
	}
	return 0
}

type ListLoanRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*LoanRequestResponse `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoanRequestsResponse) Reset() {
	*x = ListLoanRequestsResponse{}
	mi := &file_credit_credit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoanRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoanRequestsResponse) ProtoMessage() {}

func (x *ListLoanRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoanRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListLoanRequestsResponse) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{3}
}

func (x *ListLoanRequestsResponse) GetRequests() []*LoanRequestResponse {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ListLoanRequestsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ApproveLoanRequestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	EmployeeId    uint64                 `protobuf:"varint,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveLoanRequestReq) Reset() {
	*x = ApproveLoanRequestReq{}
	mi := &file_credit_credit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveLoanRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveLoanRequestReq) ProtoMessage() {}

func (x *ApproveLoanRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveLoanRequestReq.ProtoReflect.Descriptor instead.
func (*ApproveLoanRequestReq) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{4}
}

func (x *ApproveLoanRequestReq) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ApproveLoanRequestReq) GetEmployeeId() uint64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

type RejectLoanRequestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectLoanRequestReq) Reset() {
	*x = RejectLoanRequestReq{}
	mi := &file_credit_credit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectLoanRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectLoanRequestReq) ProtoMessage() {}

func (x *RejectLoanRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectLoanRequestReq.ProtoReflect.Descriptor instead.
func (*RejectLoanRequestReq) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{5}
}

func (x *RejectLoanRequestReq) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type LoanRequestResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId         uint64                 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	LoanType         string                 `protobuf:"bytes,3,opt,name=loan_type,json=loanType,proto3" json:"loan_type,omitempty"`
	InterestType     string                 `protobuf:"bytes,4,opt,name=interest_type,json=interestType,proto3" json:"interest_type,omitempty"`
	Amount           string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	CurrencyCode     string                 `protobuf:"bytes,6,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Purpose          string                 `protobuf:"bytes,7,opt,name=purpose,proto3" json:"purpose,omitempty"`
	MonthlySalary    string                 `protobuf:"bytes,8,opt,name=monthly_salary,json=monthlySalary,proto3" json:"monthly_salary,omitempty"`
	EmploymentStatus string                 `protobuf:"bytes,9,opt,name=employment_status,json=employmentStatus,proto3" json:"employment_status,omitempty"`
	EmploymentPeriod int32                  `protobuf:"varint,10,opt,name=employment_period,json=employmentPeriod,proto3" json:"employment_period,omitempty"`
	RepaymentPeriod  int32                  `protobuf:"varint,11,opt,name=repayment_period,json=repaymentPeriod,proto3" json:"repayment_period,omitempty"`
	Phone            string                 `protobuf:"bytes,12,opt,name=phone,proto3" json:"phone,omitempty"`
	AccountNumber    string                 `protobuf:"bytes,13,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Status           string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoanRequestResponse) Reset() {
	*x = LoanRequestResponse{}
	mi := &file_credit_credit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanRequestResponse) ProtoMessage() {}

func (x *LoanRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanRequestResponse.ProtoReflect.Descriptor instead.
func (*LoanRequestResponse) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{6}
}

func (x *LoanRequestResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoanRequestResponse) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *LoanRequestResponse) GetLoanType() string {
	if x != nil {
		return x.LoanType
	}
	return ""
}

func (x *LoanRequestResponse) GetInterestType() string {
	if x != nil {
		return x.InterestType
	}
	return ""
}

func (x *LoanRequestResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *LoanRequestResponse) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *LoanRequestResponse) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *LoanRequestResponse) GetMonthlySalary() string {
	if x != nil {
		return x.MonthlySalary
	}
	return ""
}

func (x *LoanRequestResponse) GetEmploymentStatus() string {
	if x != nil {
		return x.EmploymentStatus
	}
	return ""
}

func (x *LoanRequestResponse) GetEmploymentPeriod() int32 {
	if x != nil {
		return x.EmploymentPeriod
	}
	return 0
}

func (x *LoanRequestResponse) GetRepaymentPeriod() int32 {
	if x != nil {
		return x.RepaymentPeriod
	}
	return 0
}

func (x *LoanRequestResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoanRequestResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *LoanRequestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoanRequestResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetLoanReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanReq) Reset() {
	*x = GetLoanReq{}
	mi := &file_credit_credit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanReq) ProtoMessage() {}

func (x *GetLoanReq) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanReq.ProtoReflect.Descriptor instead.
func (*GetLoanReq) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{7}
}

func (x *GetLoanReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListLoansByClientReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoansByClientReq) Reset() {
	*x = ListLoansByClientReq{}
	mi := &file_credit_credit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoansByClientReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoansByClientReq) ProtoMessage() {}

func (x *ListLoansByClientReq) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoansByClientReq.ProtoReflect.Descriptor instead.
func (*ListLoansByClientReq) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{8}
}

func (x *ListLoansByClientReq) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ListLoansByClientReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLoansByClientReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListAllLoansReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LoanTypeFilter      string                 `protobuf:"bytes,1,opt,name=loan_type_filter,json=loanTypeFilter,proto3" json:"loan_type_filter,omitempty"`
	AccountNumberFilter string                 `protobuf:"bytes,2,opt,name=account_number_filter,json=accountNumberFilter,proto3" json:"account_number_filter,omitempty"`
	StatusFilter        string                 `protobuf:"bytes,3,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	Page                int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize            int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListAllLoansReq) Reset() {
	*x = ListAllLoansReq{}
	mi := &file_credit_credit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllLoansReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllLoansReq) ProtoMessage() {}

func (x *ListAllLoansReq) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllLoansReq.ProtoReflect.Descriptor instead.
func (*ListAllLoansReq) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{9}
}

func (x *ListAllLoansReq) GetLoanTypeFilter() string {
	if x != nil {
		return x.LoanTypeFilter
	}
	return ""
}

func (x *ListAllLoansReq) GetAccountNumberFilter() string {
	if x != nil {
		return x.AccountNumberFilter
	}
	return ""
}

func (x *ListAllLoansReq) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

func (x *ListAllLoansReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAllLoansReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListLoansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loans         []*LoanResponse        `protobuf:"bytes,1,rep,name=loans,proto3" json:"loans,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoansResponse) Reset() {
	*x = ListLoansResponse{}
	mi := &file_credit_credit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoansResponse) ProtoMessage() {}

func (x *ListLoansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoansResponse.ProtoReflect.Descriptor instead.
func (*ListLoansResponse) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{10}
}

func (x *ListLoansResponse) GetLoans() []*LoanResponse {
	if x != nil {
		return x.Loans
	}
	return nil
}

func (x *ListLoansResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type LoanResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LoanNumber            string                 `protobuf:"bytes,2,opt,name=loan_number,json=loanNumber,proto3" json:"loan_number,omitempty"`
	LoanType              string                 `protobuf:"bytes,3,opt,name=loan_type,json=loanType,proto3" json:"loan_type,omitempty"`
	AccountNumber         string                 `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Amount                string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	RepaymentPeriod       int32                  `protobuf:"varint,6,opt,name=repayment_period,json=repaymentPeriod,proto3" json:"repayment_period,omitempty"`
	NominalInterestRate   string                 `protobuf:"bytes,7,opt,name=nominal_interest_rate,json=nominalInterestRate,proto3" json:"nominal_interest_rate,omitempty"`
	EffectiveInterestRate string                 `protobuf:"bytes,8,opt,name=effective_interest_rate,json=effectiveInterestRate,proto3" json:"effective_interest_rate,omitempty"`
	ContractDate          string                 `protobuf:"bytes,9,opt,name=contract_date,json=contractDate,proto3" json:"contract_date,omitempty"`
	MaturityDate          string                 `protobuf:"bytes,10,opt,name=maturity_date,json=maturityDate,proto3" json:"maturity_date,omitempty"`
	NextInstallmentAmount string                 `protobuf:"bytes,11,opt,name=next_installment_amount,json=nextInstallmentAmount,proto3" json:"next_installment_amount,omitempty"`
	NextInstallmentDate   string                 `protobuf:"bytes,12,opt,name=next_installment_date,json=nextInstallmentDate,proto3" json:"next_installment_date,omitempty"`
	RemainingDebt         string                 `protobuf:"bytes,13,opt,name=remaining_debt,json=remainingDebt,proto3" json:"remaining_debt,omitempty"`
	CurrencyCode          string                 `protobuf:"bytes,14,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Status                string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	InterestType          string                 `protobuf:"bytes,16,opt,name=interest_type,json=interestType,proto3" json:"interest_type,omitempty"`
	CreatedAt             string                 `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClientId              uint64                 `protobuf:"varint,18,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // owner of the loan, used for /api/me ownership checks
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LoanResponse) Reset() {
	*x = LoanResponse{}
	mi := &file_credit_credit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanResponse) ProtoMessage() {}

func (x *LoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanResponse.ProtoReflect.Descriptor instead.
func (*LoanResponse) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{11}
}

func (x *LoanResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoanResponse) GetLoanNumber() string {
	if x != nil {
		return x.LoanNumber
	}
	return ""
}

func (x *LoanResponse) GetLoanType() string {
	if x != nil {
		return x.LoanType
	}
	return ""
}

func (x *LoanResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *LoanResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *LoanResponse) GetRepaymentPeriod() int32 {
	if x != nil {
		return x.RepaymentPeriod
	}
	return 0
}

func (x *LoanResponse) GetNominalInterestRate() string {
	if x != nil {
		return x.NominalInterestRate
	}
	return ""
}

func (x *LoanResponse) GetEffectiveInterestRate() string {
	if x != nil {
		return x.EffectiveInterestRate
	}
	return ""
}

func (x *LoanResponse) GetContractDate() string {
	if x != nil {
		return x.ContractDate
	}
	return ""
}

func (x *LoanResponse) GetMaturityDate() string {
	if x != nil {
		return x.MaturityDate
	}
	return ""
}

func (x *LoanResponse) GetNextInstallmentAmount() string {
	if x != nil {
		return x.NextInstallmentAmount
	}
	return ""
}

func (x *LoanResponse) GetNextInstallmentDate() string {
	if x != nil {
		return x.NextInstallmentDate
	}
	return ""
}

func (x *LoanResponse) GetRemainingDebt() string {
	if x != nil {
		return x.RemainingDebt
	}
	return ""
}

func (x *LoanResponse) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *LoanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoanResponse) GetInterestType() string {
	if x != nil {
		return x.InterestType
	}
	return ""
}

func (x *LoanResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LoanResponse) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type GetInstallmentsByLoanReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        uint64                 `protobuf:"varint,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstallmentsByLoanReq) Reset() {
	*x = GetInstallmentsByLoanReq{}
	mi := &file_credit_credit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstallmentsByLoanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstallmentsByLoanReq) ProtoMessage() {}

func (x *GetInstallmentsByLoanReq) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstallmentsByLoanReq.ProtoReflect.Descriptor instead.
func (*GetInstallmentsByLoanReq) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{12}
}

func (x *GetInstallmentsByLoanReq) GetLoanId() uint64 {
	if x != nil {
		return x.LoanId
	}
	return 0
}

type ListInstallmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Installments  []*InstallmentResponse `protobuf:"bytes,1,rep,name=installments,proto3" json:"installments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstallmentsResponse) Reset() {
	*x = ListInstallmentsResponse{}
	mi := &file_credit_credit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstallmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstallmentsResponse) ProtoMessage() {}

func (x *ListInstallmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstallmentsResponse.ProtoReflect.Descriptor instead.
func (*ListInstallmentsResponse) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{13}
}

func (x *ListInstallmentsResponse) GetInstallments() []*InstallmentResponse {
	if x != nil {
		return x.Installments
	}
	return nil
}

type InstallmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LoanId        uint64                 `protobuf:"varint,2,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	InterestRate  string                 `protobuf:"bytes,4,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,5,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	ExpectedDate  string                 `protobuf:"bytes,6,opt,name=expected_date,json=expectedDate,proto3" json:"expected_date,omitempty"`
	ActualDate    string                 `protobuf:"bytes,7,opt,name=actual_date,json=actualDate,proto3" json:"actual_date,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallmentResponse) Reset() {
	*x = InstallmentResponse{}
	mi := &file_credit_credit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallmentResponse) ProtoMessage() {}

func (x *InstallmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallmentResponse.ProtoReflect.Descriptor instead.
func (*InstallmentResponse) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{14}
}

func (x *InstallmentResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InstallmentResponse) GetLoanId() uint64 {
	if x != nil {
		return x.LoanId
	}
	return 0
}

func (x *InstallmentResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *InstallmentResponse) GetInterestRate() string {
	if x != nil {
		return x.InterestRate
	}
	return ""
}

func (x *InstallmentResponse) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *InstallmentResponse) GetExpectedDate() string {
	if x != nil {
		return x.ExpectedDate
	}
	return ""
}

func (x *InstallmentResponse) GetActualDate() string {
	if x != nil {
		return x.ActualDate
	}
	return ""
}

func (x *InstallmentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListInterestRateTiersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterestRateTiersRequest) Reset() {
	*x = ListInterestRateTiersRequest{}
	mi := &file_credit_credit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterestRateTiersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterestRateTiersRequest) ProtoMessage() {}

func (x *ListInterestRateTiersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterestRateTiersRequest.ProtoReflect.Descriptor instead.
func (*ListInterestRateTiersRequest) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{15}
}

type ListInterestRateTiersResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Tiers         []*InterestRateTierResponse `protobuf:"bytes,1,rep,name=tiers,proto3" json:"tiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterestRateTiersResponse) Reset() {
	*x = ListInterestRateTiersResponse{}
	mi := &file_credit_credit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterestRateTiersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterestRateTiersResponse) ProtoMessage() {}

func (x *ListInterestRateTiersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterestRateTiersResponse.ProtoReflect.Descriptor instead.
func (*ListInterestRateTiersResponse) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{16}
}

func (x *ListInterestRateTiersResponse) GetTiers() []*InterestRateTierResponse {
	if x != nil {
		return x.Tiers
	}
	return nil
}

type InterestRateTierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AmountFrom    string                 `protobuf:"bytes,2,opt,name=amount_from,json=amountFrom,proto3" json:"amount_from,omitempty"`
	AmountTo      string                 `protobuf:"bytes,3,opt,name=amount_to,json=amountTo,proto3" json:"amount_to,omitempty"`
	FixedRate     string                 `protobuf:"bytes,4,opt,name=fixed_rate,json=fixedRate,proto3" json:"fixed_rate,omitempty"`
	VariableBase  string                 `protobuf:"bytes,5,opt,name=variable_base,json=variableBase,proto3" json:"variable_base,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterestRateTierResponse) Reset() {
	*x = InterestRateTierResponse{}
	mi := &file_credit_credit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterestRateTierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterestRateTierResponse) ProtoMessage() {}

func (x *InterestRateTierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterestRateTierResponse.ProtoReflect.Descriptor instead.
func (*InterestRateTierResponse) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{17}
}

func (x *InterestRateTierResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InterestRateTierResponse) GetAmountFrom() string {
	if x != nil {
		return x.AmountFrom
	}
	return ""
}

func (x *InterestRateTierResponse) GetAmountTo() string {
	if x != nil {
		return x.AmountTo
	}
	return ""
}

func (x *InterestRateTierResponse) GetFixedRate() string {
	if x != nil {
		return x.FixedRate
	}
	return ""
}

func (x *InterestRateTierResponse) GetVariableBase() string {
	if x != nil {
		return x.VariableBase
	}
	return ""
}

func (x *InterestRateTierResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *InterestRateTierResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *InterestRateTierResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateInterestRateTierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountFrom    string                 `protobuf:"bytes,1,opt,name=amount_from,json=amountFrom,proto3" json:"amount_from,omitempty"`
	AmountTo      string                 `protobuf:"bytes,2,opt,name=amount_to,json=amountTo,proto3" json:"amount_to,omitempty"`
	FixedRate     string                 `protobuf:"bytes,3,opt,name=fixed_rate,json=fixedRate,proto3" json:"fixed_rate,omitempty"`
	VariableBase  string                 `protobuf:"bytes,4,opt,name=variable_base,json=variableBase,proto3" json:"variable_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInterestRateTierRequest) Reset() {
	*x = CreateInterestRateTierRequest{}
	mi := &file_credit_credit_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInterestRateTierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInterestRateTierRequest) ProtoMessage() {}

func (x *CreateInterestRateTierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInterestRateTierRequest.ProtoReflect.Descriptor instead.
func (*CreateInterestRateTierRequest) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{18}
}

func (x *CreateInterestRateTierRequest) GetAmountFrom() string {
	if x != nil {
		return x.AmountFrom
	}
	return ""
}

func (x *CreateInterestRateTierRequest) GetAmountTo() string {
	if x != nil {
		return x.AmountTo
	}
	return ""
}

func (x *CreateInterestRateTierRequest) GetFixedRate() string {
	if x != nil {
		return x.FixedRate
	}
	return ""
}

func (x *CreateInterestRateTierRequest) GetVariableBase() string {
	if x != nil {
		return x.VariableBase
	}
	return ""
}

type UpdateInterestRateTierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AmountFrom    string                 `protobuf:"bytes,2,opt,name=amount_from,json=amountFrom,proto3" json:"amount_from,omitempty"`
	AmountTo      string                 `protobuf:"bytes,3,opt,name=amount_to,json=amountTo,proto3" json:"amount_to,omitempty"`
	FixedRate     string                 `protobuf:"bytes,4,opt,name=fixed_rate,json=fixedRate,proto3" json:"fixed_rate,omitempty"`
	VariableBase  string                 `protobuf:"bytes,5,opt,name=variable_base,json=variableBase,proto3" json:"variable_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInterestRateTierRequest) Reset() {
	*x = UpdateInterestRateTierRequest{}
	mi := &file_credit_credit_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInterestRateTierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInterestRateTierRequest) ProtoMessage() {}

func (x *UpdateInterestRateTierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInterestRateTierRequest.ProtoReflect.Descriptor instead.
func (*UpdateInterestRateTierRequest) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateInterestRateTierRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateInterestRateTierRequest) GetAmountFrom() string {
	if x != nil {
		return x.AmountFrom
	}
	return ""
}

func (x *UpdateInterestRateTierRequest) GetAmountTo() string {
	if x != nil {
		return x.AmountTo
	}
	return ""
}

func (x *UpdateInterestRateTierRequest) GetFixedRate() string {
	if x != nil {
		return x.FixedRate
	}
	return ""
}

func (x *UpdateInterestRateTierRequest) GetVariableBase() string {
	if x != nil {
		return x.VariableBase
	}
	return ""
}

type DeleteInterestRateTierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInterestRateTierRequest) Reset() {
	*x = DeleteInterestRateTierRequest{}
	mi := &file_credit_credit_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInterestRateTierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInterestRateTierRequest) ProtoMessage() {}

func (x *DeleteInterestRateTierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInterestRateTierRequest.ProtoReflect.Descriptor instead.
func (*DeleteInterestRateTierRequest) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteInterestRateTierRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_credit_credit_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListBankMarginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBankMarginsRequest) Reset() {
	*x = ListBankMarginsRequest{}
	mi := &file_credit_credit_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBankMarginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBankMarginsRequest) ProtoMessage() {}

func (x *ListBankMarginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBankMarginsRequest.ProtoReflect.Descriptor instead.
func (*ListBankMarginsRequest) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{22}
}

type ListBankMarginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Margins       []*BankMarginResponse  `protobuf:"bytes,1,rep,name=margins,proto3" json:"margins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBankMarginsResponse) Reset() {
	*x = ListBankMarginsResponse{}
	mi := &file_credit_credit_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBankMarginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBankMarginsResponse) ProtoMessage() {}

func (x *ListBankMarginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBankMarginsResponse.ProtoReflect.Descriptor instead.
func (*ListBankMarginsResponse) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{23}
}

func (x *ListBankMarginsResponse) GetMargins() []*BankMarginResponse {
	if x != nil {
		return x.Margins
	}
	return nil
}

type BankMarginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LoanType      string                 `protobuf:"bytes,2,opt,name=loan_type,json=loanType,proto3" json:"loan_type,omitempty"`
	Margin        string                 `protobuf:"bytes,3,opt,name=margin,proto3" json:"margin,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankMarginResponse) Reset() {
	*x = BankMarginResponse{}
	mi := &file_credit_credit_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankMarginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankMarginResponse) ProtoMessage() {}

func (x *BankMarginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankMarginResponse.ProtoReflect.Descriptor instead.
func (*BankMarginResponse) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{24}
}

func (x *BankMarginResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BankMarginResponse) GetLoanType() string {
	if x != nil {
		return x.LoanType
	}
	return ""
}

func (x *BankMarginResponse) GetMargin() string {
	if x != nil {
		return x.Margin
	}
	return ""
}

func (x *BankMarginResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *BankMarginResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BankMarginResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UpdateBankMarginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Margin        string                 `protobuf:"bytes,2,opt,name=margin,proto3" json:"margin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBankMarginRequest) Reset() {
	*x = UpdateBankMarginRequest{}
	mi := &file_credit_credit_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBankMarginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBankMarginRequest) ProtoMessage() {}

func (x *UpdateBankMarginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBankMarginRequest.ProtoReflect.Descriptor instead.
func (*UpdateBankMarginRequest) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateBankMarginRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBankMarginRequest) GetMargin() string {
	if x != nil {
		return x.Margin
	}
	return ""
}

type ApplyVariableRateUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TierId        uint64                 `protobuf:"varint,1,opt,name=tier_id,json=tierId,proto3" json:"tier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyVariableRateUpdateRequest) Reset() {
	*x = ApplyVariableRateUpdateRequest{}
	mi := &file_credit_credit_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyVariableRateUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyVariableRateUpdateRequest) ProtoMessage() {}

func (x *ApplyVariableRateUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyVariableRateUpdateRequest.ProtoReflect.Descriptor instead.
func (*ApplyVariableRateUpdateRequest) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{26}
}

func (x *ApplyVariableRateUpdateRequest) GetTierId() uint64 {
	if x != nil {
		return x.TierId
	}
	return 0
}

type ApplyVariableRateUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffectedLoans int32                  `protobuf:"varint,1,opt,name=affected_loans,json=affectedLoans,proto3" json:"affected_loans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyVariableRateUpdateResponse) Reset() {
	*x = ApplyVariableRateUpdateResponse{}
	mi := &file_credit_credit_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyVariableRateUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyVariableRateUpdateResponse) ProtoMessage() {}

func (x *ApplyVariableRateUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_credit_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyVariableRateUpdateResponse.ProtoReflect.Descriptor instead.
func (*ApplyVariableRateUpdateResponse) Descriptor() ([]byte, []int) {
	return file_credit_credit_proto_rawDescGZIP(), []int{27}
}

func (x *ApplyVariableRateUpdateResponse) GetAffectedLoans() int32 {
	if x != nil {
		return x.AffectedLoans
	}
	return 0
}

var File_credit_credit_proto protoreflect.FileDescriptor

const file_credit_credit_proto_rawDesc = "" +
	"\n" +
	"\x13credit/credit.proto\x12\x06credit\"\xb5\x03\n" +
	"\x14CreateLoanRequestReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x1b\n" +
	"\tloan_type\x18\x02 \x01(\tR\bloanType\x12#\n" +
	"\rinterest_type\x18\x03 \x01(\tR\finterestType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12#\n" +
	"\rcurrency_code\x18\x05 \x01(\tR\fcurrencyCode\x12\x18\n" +
	"\apurpose\x18\x06 \x01(\tR\apurpose\x12%\n" +
	"\x0emonthly_salary\x18\a \x01(\tR\rmonthlySalary\x12+\n" +
	"\x11employment_status\x18\b \x01(\tR\x10employmentStatus\x12+\n" +
	"\x11employment_period\x18\t \x01(\x05R\x10employmentPeriod\x12)\n" +
	"\x10repayment_period\x18\n" +
	" \x01(\x05R\x0frepaymentPeriod\x12\x14\n" +
	"\x05phone\x18\v \x01(\tR\x05phone\x12%\n" +
	"\x0eaccount_number\x18\f \x01(\tR\raccountNumber\"#\n" +
	"\x11GetLoanRequestReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xf3\x01\n" +
	"\x13ListLoanRequestsReq\x12(\n" +
	"\x10loan_type_filter\x18\x01 \x01(\tR\x0eloanTypeFilter\x122\n" +
	"\x15account_number_filter\x18\x02 \x01(\tR\x13accountNumberFilter\x12#\n" +
	"\rstatus_filter\x18\x03 \x01(\tR\fstatusFilter\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12(\n" +
	"\x10client_id_filter\x18\x06 \x01(\x04R\x0eclientIdFilter\"i\n" +
	"\x18ListLoanRequestsResponse\x127\n" +
	"\brequests\x18\x01 \x03(\v2\x1b.credit.LoanRequestResponseR\brequests\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"W\n" +
	"\x15ApproveLoanRequestReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x01(\x04R\n" +
	"employeeId\"5\n" +
	"\x14RejectLoanRequestReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\"\xfb\x03\n" +
	"\x13LoanRequestResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x04R\bclientId\x12\x1b\n" +
	"\tloan_type\x18\x03 \x01(\tR\bloanType\x12#\n" +
	"\rinterest_type\x18\x04 \x01(\tR\finterestType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12#\n" +
	"\rcurrency_code\x18\x06 \x01(\tR\fcurrencyCode\x12\x18\n" +
	"\apurpose\x18\a \x01(\tR\apurpose\x12%\n" +
	"\x0emonthly_salary\x18\b \x01(\tR\rmonthlySalary\x12+\n" +
	"\x11employment_status\x18\t \x01(\tR\x10employmentStatus\x12+\n" +
	"\x11employment_period\x18\n" +
	" \x01(\x05R\x10employmentPeriod\x12)\n" +
	"\x10repayment_period\x18\v \x01(\x05R\x0frepaymentPeriod\x12\x14\n" +
	"\x05phone\x18\f \x01(\tR\x05phone\x12%\n" +
	"\x0eaccount_number\x18\r \x01(\tR\raccountNumber\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\"\x1c\n" +
	"\n" +
	"GetLoanReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"d\n" +
	"\x14ListLoansByClientReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xc5\x01\n" +
	"\x0fListAllLoansReq\x12(\n" +
	"\x10loan_type_filter\x18\x01 \x01(\tR\x0eloanTypeFilter\x122\n" +
	"\x15account_number_filter\x18\x02 \x01(\tR\x13accountNumberFilter\x12#\n" +
	"\rstatus_filter\x18\x03 \x01(\tR\fstatusFilter\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"U\n" +
	"\x11ListLoansResponse\x12*\n" +
	"\x05loans\x18\x01 \x03(\v2\x14.credit.LoanResponseR\x05loans\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xad\x05\n" +
	"\fLoanResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vloan_number\x18\x02 \x01(\tR\n" +
	"loanNumber\x12\x1b\n" +
	"\tloan_type\x18\x03 \x01(\tR\bloanType\x12%\n" +
	"\x0eaccount_number\x18\x04 \x01(\tR\raccountNumber\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12)\n" +
	"\x10repayment_period\x18\x06 \x01(\x05R\x0frepaymentPeriod\x122\n" +
	"\x15nominal_interest_rate\x18\a \x01(\tR\x13nominalInterestRate\x126\n" +
	"\x17effective_interest_rate\x18\b \x01(\tR\x15effectiveInterestRate\x12#\n" +
	"\rcontract_date\x18\t \x01(\tR\fcontractDate\x12#\n" +
	"\rmaturity_date\x18\n" +
	" \x01(\tR\fmaturityDate\x126\n" +
	"\x17next_installment_amount\x18\v \x01(\tR\x15nextInstallmentAmount\x122\n" +
	"\x15next_installment_date\x18\f \x01(\tR\x13nextInstallmentDate\x12%\n" +
	"\x0eremaining_debt\x18\r \x01(\tR\rremainingDebt\x12#\n" +
	"\rcurrency_code\x18\x0e \x01(\tR\fcurrencyCode\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12#\n" +
	"\rinterest_type\x18\x10 \x01(\tR\finterestType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x11 \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tclient_id\x18\x12 \x01(\x04R\bclientId\"3\n" +
	"\x18GetInstallmentsByLoanReq\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\x04R\x06loanId\"[\n" +
	"\x18ListInstallmentsResponse\x12?\n" +
	"\finstallments\x18\x01 \x03(\v2\x1b.credit.InstallmentResponseR\finstallments\"\xfe\x01\n" +
	"\x13InstallmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\aloan_id\x18\x02 \x01(\x04R\x06loanId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12#\n" +
	"\rinterest_rate\x18\x04 \x01(\tR\finterestRate\x12#\n" +
	"\rcurrency_code\x18\x05 \x01(\tR\fcurrencyCode\x12#\n" +
	"\rexpected_date\x18\x06 \x01(\tR\fexpectedDate\x12\x1f\n" +
	"\vactual_date\x18\a \x01(\tR\n" +
	"actualDate\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"\x1e\n" +
	"\x1cListInterestRateTiersRequest\"W\n" +
	"\x1dListInterestRateTiersResponse\x126\n" +
	"\x05tiers\x18\x01 \x03(\v2 .credit.InterestRateTierResponseR\x05tiers\"\x82\x02\n" +
	"\x18InterestRateTierResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vamount_from\x18\x02 \x01(\tR\n" +
	"amountFrom\x12\x1b\n" +
	"\tamount_to\x18\x03 \x01(\tR\bamountTo\x12\x1d\n" +
	"\n" +
	"fixed_rate\x18\x04 \x01(\tR\tfixedRate\x12#\n" +
	"\rvariable_base\x18\x05 \x01(\tR\fvariableBase\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\xa1\x01\n" +
	"\x1dCreateInterestRateTierRequest\x12\x1f\n" +
	"\vamount_from\x18\x01 \x01(\tR\n" +
	"amountFrom\x12\x1b\n" +
	"\tamount_to\x18\x02 \x01(\tR\bamountTo\x12\x1d\n" +
	"\n" +
	"fixed_rate\x18\x03 \x01(\tR\tfixedRate\x12#\n" +
	"\rvariable_base\x18\x04 \x01(\tR\fvariableBase\"\xb1\x01\n" +
	"\x1dUpdateInterestRateTierRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vamount_from\x18\x02 \x01(\tR\n" +
	"amountFrom\x12\x1b\n" +
	"\tamount_to\x18\x03 \x01(\tR\bamountTo\x12\x1d\n" +
	"\n" +
	"fixed_rate\x18\x04 \x01(\tR\tfixedRate\x12#\n" +
	"\rvariable_base\x18\x05 \x01(\tR\fvariableBase\"/\n" +
	"\x1dDeleteInterestRateTierRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x18\n" +
	"\x16ListBankMarginsRequest\"O\n" +
	"\x17ListBankMarginsResponse\x124\n" +
	"\amargins\x18\x01 \x03(\v2\x1a.credit.BankMarginResponseR\amargins\"\xaf\x01\n" +
	"\x12BankMarginResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tloan_type\x18\x02 \x01(\tR\bloanType\x12\x16\n" +
	"\x06margin\x18\x03 \x01(\tR\x06margin\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"A\n" +
	"\x17UpdateBankMarginRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06margin\x18\x02 \x01(\tR\x06margin\"9\n" +
	"\x1eApplyVariableRateUpdateRequest\x12\x17\n" +
	"\atier_id\x18\x01 \x01(\x04R\x06tierId\"H\n" +
	"\x1fApplyVariableRateUpdateResponse\x12%\n" +
	"\x0eaffected_loans\x18\x01 \x01(\x05R\raffectedLoans2\xd1\n" +
	"\n" +
	"\rCreditService\x12N\n" +
	"\x11CreateLoanRequest\x12\x1c.credit.CreateLoanRequestReq\x1a\x1b.credit.LoanRequestResponse\x12H\n" +
	"\x0eGetLoanRequest\x12\x19.credit.GetLoanRequestReq\x1a\x1b.credit.LoanRequestResponse\x12Q\n" +
	"\x10ListLoanRequests\x12\x1b.credit.ListLoanRequestsReq\x1a .credit.ListLoanRequestsResponse\x12I\n" +
	"\x12ApproveLoanRequest\x12\x1d.credit.ApproveLoanRequestReq\x1a\x14.credit.LoanResponse\x12N\n" +
	"\x11RejectLoanRequest\x12\x1c.credit.RejectLoanRequestReq\x1a\x1b.credit.LoanRequestResponse\x123\n" +
	"\aGetLoan\x12\x12.credit.GetLoanReq\x1a\x14.credit.LoanResponse\x12L\n" +
	"\x11ListLoansByClient\x12\x1c.credit.ListLoansByClientReq\x1a\x19.credit.ListLoansResponse\x12B\n" +
	"\fListAllLoans\x12\x17.credit.ListAllLoansReq\x1a\x19.credit.ListLoansResponse\x12[\n" +
	"\x15GetInstallmentsByLoan\x12 .credit.GetInstallmentsByLoanReq\x1a .credit.ListInstallmentsResponse\x12d\n" +
	"\x15ListInterestRateTiers\x12$.credit.ListInterestRateTiersRequest\x1a%.credit.ListInterestRateTiersResponse\x12a\n" +
	"\x16CreateInterestRateTier\x12%.credit.CreateInterestRateTierRequest\x1a .credit.InterestRateTierResponse\x12a\n" +
	"\x16UpdateInterestRateTier\x12%.credit.UpdateInterestRateTierRequest\x1a .credit.InterestRateTierResponse\x12W\n" +
	"\x16DeleteInterestRateTier\x12%.credit.DeleteInterestRateTierRequest\x1a\x16.credit.DeleteResponse\x12R\n" +
	"\x0fListBankMargins\x12\x1e.credit.ListBankMarginsRequest\x1a\x1f.credit.ListBankMarginsResponse\x12O\n" +
	"\x10UpdateBankMargin\x12\x1f.credit.UpdateBankMarginRequest\x1a\x1a.credit.BankMarginResponse\x12j\n" +
	"\x17ApplyVariableRateUpdate\x12&.credit.ApplyVariableRateUpdateRequest\x1a'.credit.ApplyVariableRateUpdateResponseB/Z-github.com/exbanka/contract/creditpb;creditpbb\x06proto3"

var (
	file_credit_credit_proto_rawDescOnce sync.Once
	file_credit_credit_proto_rawDescData []byte
)

func file_credit_credit_proto_rawDescGZIP() []byte {
	file_credit_credit_proto_rawDescOnce.Do(func() {
		file_credit_credit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credit_credit_proto_rawDesc), len(file_credit_credit_proto_rawDesc)))
	})
	return file_credit_credit_proto_rawDescData
}

var file_credit_credit_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_credit_credit_proto_goTypes = []any{
	(*CreateLoanRequestReq)(nil),            // 0: credit.CreateLoanRequestReq
	(*GetLoanRequestReq)(nil),               // 1: credit.GetLoanRequestReq
	(*ListLoanRequestsReq)(nil),             // 2: credit.ListLoanRequestsReq
	(*ListLoanRequestsResponse)(nil),        // 3: credit.ListLoanRequestsResponse
	(*ApproveLoanRequestReq)(nil),           // 4: credit.ApproveLoanRequestReq
	(*RejectLoanRequestReq)(nil),            // 5: credit.RejectLoanRequestReq
	(*LoanRequestResponse)(nil),             // 6: credit.LoanRequestResponse
	(*GetLoanReq)(nil),                      // 7: credit.GetLoanReq
	(*ListLoansByClientReq)(nil),            // 8: credit.ListLoansByClientReq
	(*ListAllLoansReq)(nil),                 // 9: credit.ListAllLoansReq
	(*ListLoansResponse)(nil),               // 10: credit.ListLoansResponse
	(*LoanResponse)(nil),                    // 11: credit.LoanResponse
	(*GetInstallmentsByLoanReq)(nil),        // 12: credit.GetInstallmentsByLoanReq
	(*ListInstallmentsResponse)(nil),        // 13: credit.ListInstallmentsResponse
	(*InstallmentResponse)(nil),             // 14: credit.InstallmentResponse
	(*ListInterestRateTiersRequest)(nil),    // 15: credit.ListInterestRateTiersRequest
	(*ListInterestRateTiersResponse)(nil),   // 16: credit.ListInterestRateTiersResponse
	(*InterestRateTierResponse)(nil),        // 17: credit.InterestRateTierResponse
	(*CreateInterestRateTierRequest)(nil),   // 18: credit.CreateInterestRateTierRequest
	(*UpdateInterestRateTierRequest)(nil),   // 19: credit.UpdateInterestRateTierRequest
	(*DeleteInterestRateTierRequest)(nil),   // 20: credit.DeleteInterestRateTierRequest
	(*DeleteResponse)(nil),                  // 21: credit.DeleteResponse
	(*ListBankMarginsRequest)(nil),          // 22: credit.ListBankMarginsRequest
	(*ListBankMarginsResponse)(nil),         // 23: credit.ListBankMarginsResponse
	(*BankMarginResponse)(nil),              // 24: credit.BankMarginResponse
	(*UpdateBankMarginRequest)(nil),         // 25: credit.UpdateBankMarginRequest
	(*ApplyVariableRateUpdateRequest)(nil),  // 26: credit.ApplyVariableRateUpdateRequest
	(*ApplyVariableRateUpdateResponse)(nil), // 27: credit.ApplyVariableRateUpdateResponse
}
var file_credit_credit_proto_depIdxs = []int32{
	6,  // 0: credit.ListLoanRequestsResponse.requests:type_name -> credit.LoanRequestResponse
	11, // 1: credit.ListLoansResponse.loans:type_name -> credit.LoanResponse
	14, // 2: credit.ListInstallmentsResponse.installments:type_name -> credit.InstallmentResponse
	17, // 3: credit.ListInterestRateTiersResponse.tiers:type_name -> credit.InterestRateTierResponse
	24, // 4: credit.ListBankMarginsResponse.margins:type_name -> credit.BankMarginResponse
	0,  // 5: credit.CreditService.CreateLoanRequest:input_type -> credit.CreateLoanRequestReq
	1,  // 6: credit.CreditService.GetLoanRequest:input_type -> credit.GetLoanRequestReq
	2,  // 7: credit.CreditService.ListLoanRequests:input_type -> credit.ListLoanRequestsReq
	4,  // 8: credit.CreditService.ApproveLoanRequest:input_type -> credit.ApproveLoanRequestReq
	5,  // 9: credit.CreditService.RejectLoanRequest:input_type -> credit.RejectLoanRequestReq
	7,  // 10: credit.CreditService.GetLoan:input_type -> credit.GetLoanReq
	8,  // 11: credit.CreditService.ListLoansByClient:input_type -> credit.ListLoansByClientReq
	9,  // 12: credit.CreditService.ListAllLoans:input_type -> credit.ListAllLoansReq
	12, // 13: credit.CreditService.GetInstallmentsByLoan:input_type -> credit.GetInstallmentsByLoanReq
	15, // 14: credit.CreditService.ListInterestRateTiers:input_type -> credit.ListInterestRateTiersRequest
	18, // 15: credit.CreditService.CreateInterestRateTier:input_type -> credit.CreateInterestRateTierRequest
	19, // 16: credit.CreditService.UpdateInterestRateTier:input_type -> credit.UpdateInterestRateTierRequest
	20, // 17: credit.CreditService.DeleteInterestRateTier:input_type -> credit.DeleteInterestRateTierRequest
	22, // 18: credit.CreditService.ListBankMargins:input_type -> credit.ListBankMarginsRequest
	25, // 19: credit.CreditService.UpdateBankMargin:input_type -> credit.UpdateBankMarginRequest
	26, // 20: credit.CreditService.ApplyVariableRateUpdate:input_type -> credit.ApplyVariableRateUpdateRequest
	6,  // 21: credit.CreditService.CreateLoanRequest:output_type -> credit.LoanRequestResponse
	6,  // 22: credit.CreditService.GetLoanRequest:output_type -> credit.LoanRequestResponse
	3,  // 23: credit.CreditService.ListLoanRequests:output_type -> credit.ListLoanRequestsResponse
	11, // 24: credit.CreditService.ApproveLoanRequest:output_type -> credit.LoanResponse
	6,  // 25: credit.CreditService.RejectLoanRequest:output_type -> credit.LoanRequestResponse
	11, // 26: credit.CreditService.GetLoan:output_type -> credit.LoanResponse
	10, // 27: credit.CreditService.ListLoansByClient:output_type -> credit.ListLoansResponse
	10, // 28: credit.CreditService.ListAllLoans:output_type -> credit.ListLoansResponse
	13, // 29: credit.CreditService.GetInstallmentsByLoan:output_type -> credit.ListInstallmentsResponse
	16, // 30: credit.CreditService.ListInterestRateTiers:output_type -> credit.ListInterestRateTiersResponse
	17, // 31: credit.CreditService.CreateInterestRateTier:output_type -> credit.InterestRateTierResponse
	17, // 32: credit.CreditService.UpdateInterestRateTier:output_type -> credit.InterestRateTierResponse
	21, // 33: credit.CreditService.DeleteInterestRateTier:output_type -> credit.DeleteResponse
	23, // 34: credit.CreditService.ListBankMargins:output_type -> credit.ListBankMarginsResponse
	24, // 35: credit.CreditService.UpdateBankMargin:output_type -> credit.BankMarginResponse
	27, // 36: credit.CreditService.ApplyVariableRateUpdate:output_type -> credit.ApplyVariableRateUpdateResponse
	21, // [21:37] is the sub-list for method output_type
	5,  // [5:21] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_credit_credit_proto_init() }
func file_credit_credit_proto_init() {
	if File_credit_credit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credit_credit_proto_rawDesc), len(file_credit_credit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_credit_credit_proto_goTypes,
		DependencyIndexes: file_credit_credit_proto_depIdxs,
		MessageInfos:      file_credit_credit_proto_msgTypes,
	}.Build()
	File_credit_credit_proto = out.File
	file_credit_credit_proto_goTypes = nil
	file_credit_credit_proto_depIdxs = nil
}
