// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: client/client.proto

package clientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   int64                  `protobuf:"varint,3,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Jmbg          string                 `protobuf:"bytes,8,opt,name=jmbg,proto3" json:"jmbg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
	mi := &file_client_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{0}
}

func (x *CreateClientRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateClientRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateClientRequest) GetDateOfBirth() int64 {
	if x != nil {
		return x.DateOfBirth
	}
	return 0
}

func (x *CreateClientRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateClientRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateClientRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateClientRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateClientRequest) GetJmbg() string {
	if x != nil {
		return x.Jmbg
	}
	return ""
}

type GetClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientRequest) Reset() {
	*x = GetClientRequest{}
	mi := &file_client_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientRequest) ProtoMessage() {}

func (x *GetClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientRequest.ProtoReflect.Descriptor instead.
func (*GetClientRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{1}
}

func (x *GetClientRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetClientByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientByEmailRequest) Reset() {
	*x = GetClientByEmailRequest{}
	mi := &file_client_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientByEmailRequest) ProtoMessage() {}

func (x *GetClientByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetClientByEmailRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{2}
}

func (x *GetClientByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ListClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailFilter   string                 `protobuf:"bytes,1,opt,name=email_filter,json=emailFilter,proto3" json:"email_filter,omitempty"`
	NameFilter    string                 `protobuf:"bytes,2,opt,name=name_filter,json=nameFilter,proto3" json:"name_filter,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsRequest) Reset() {
	*x = ListClientsRequest{}
	mi := &file_client_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsRequest) ProtoMessage() {}

func (x *ListClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsRequest.ProtoReflect.Descriptor instead.
func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{3}
}

func (x *ListClientsRequest) GetEmailFilter() string {
	if x != nil {
		return x.EmailFilter
	}
	return ""
}

func (x *ListClientsRequest) GetNameFilter() string {
	if x != nil {
		return x.NameFilter
	}
	return ""
}

func (x *ListClientsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListClientsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*ClientResponse      `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsResponse) Reset() {
	*x = ListClientsResponse{}
	mi := &file_client_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsResponse) ProtoMessage() {}

func (x *ListClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsResponse.ProtoReflect.Descriptor instead.
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{4}
}

func (x *ListClientsResponse) GetClients() []*ClientResponse {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *ListClientsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     *string                `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	DateOfBirth   *int64                 `protobuf:"varint,4,opt,name=date_of_birth,json=dateOfBirth,proto3,oneof" json:"date_of_birth,omitempty"`
	Gender        *string                `protobuf:"bytes,5,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	Email         *string                `protobuf:"bytes,6,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,7,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Address       *string                `protobuf:"bytes,8,opt,name=address,proto3,oneof" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientRequest) Reset() {
	*x = UpdateClientRequest{}
	mi := &file_client_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientRequest) ProtoMessage() {}

func (x *UpdateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientRequest.ProtoReflect.Descriptor instead.
func (*UpdateClientRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateClientRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateClientRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateClientRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UpdateClientRequest) GetDateOfBirth() int64 {
	if x != nil && x.DateOfBirth != nil {
		return *x.DateOfBirth
	}
	return 0
}

func (x *UpdateClientRequest) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *UpdateClientRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateClientRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UpdateClientRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

type ClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   int64                  `protobuf:"varint,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Jmbg          string                 `protobuf:"bytes,9,opt,name=jmbg,proto3" json:"jmbg,omitempty"`
	Active        bool                   `protobuf:"varint,10,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientResponse) Reset() {
	*x = ClientResponse{}
	mi := &file_client_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponse) ProtoMessage() {}

func (x *ClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponse.ProtoReflect.Descriptor instead.
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{6}
}

func (x *ClientResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ClientResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ClientResponse) GetDateOfBirth() int64 {
	if x != nil {
		return x.DateOfBirth
	}
	return 0
}

func (x *ClientResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *ClientResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ClientResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ClientResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClientResponse) GetJmbg() string {
	if x != nil {
		return x.Jmbg
	}
	return ""
}

func (x *ClientResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ClientResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ValidateClientCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateClientCredentialsRequest) Reset() {
	*x = ValidateClientCredentialsRequest{}
	mi := &file_client_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateClientCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateClientCredentialsRequest) ProtoMessage() {}

func (x *ValidateClientCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateClientCredentialsRequest.ProtoReflect.Descriptor instead.
func (*ValidateClientCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateClientCredentialsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ValidateClientCredentialsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ValidateClientCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateClientCredentialsResponse) Reset() {
	*x = ValidateClientCredentialsResponse{}
	mi := &file_client_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateClientCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateClientCredentialsResponse) ProtoMessage() {}

func (x *ValidateClientCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateClientCredentialsResponse.ProtoReflect.Descriptor instead.
func (*ValidateClientCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateClientCredentialsResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ValidateClientCredentialsResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ValidateClientCredentialsResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ValidateClientCredentialsResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type SetClientPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClientPasswordRequest) Reset() {
	*x = SetClientPasswordRequest{}
	mi := &file_client_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClientPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClientPasswordRequest) ProtoMessage() {}

func (x *SetClientPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClientPasswordRequest.ProtoReflect.Descriptor instead.
func (*SetClientPasswordRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{9}
}

func (x *SetClientPasswordRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetClientPasswordRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type SetClientPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClientPasswordResponse) Reset() {
	*x = SetClientPasswordResponse{}
	mi := &file_client_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClientPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClientPasswordResponse) ProtoMessage() {}

func (x *SetClientPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClientPasswordResponse.ProtoReflect.Descriptor instead.
func (*SetClientPasswordResponse) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{10}
}

func (x *SetClientPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_client_client_proto protoreflect.FileDescriptor

const file_client_client_proto_rawDesc = "" +
	"\n" +
	"\x13client/client.proto\x12\x06client\"\xe7\x01\n" +
	"\x13CreateClientRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x03 \x01(\x03R\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12\x12\n" +
	"\x04jmbg\x18\b \x01(\tR\x04jmbg\"\"\n" +
	"\x10GetClientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"/\n" +
	"\x17GetClientByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x89\x01\n" +
	"\x12ListClientsRequest\x12!\n" +
	"\femail_filter\x18\x01 \x01(\tR\vemailFilter\x12\x1f\n" +
	"\vname_filter\x18\x02 \x01(\tR\n" +
	"nameFilter\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"]\n" +
	"\x13ListClientsResponse\x120\n" +
	"\aclients\x18\x01 \x03(\v2\x16.client.ClientResponseR\aclients\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xe0\x02\n" +
	"\x13UpdateClientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\"\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x03 \x01(\tH\x01R\blastName\x88\x01\x01\x12'\n" +
	"\rdate_of_birth\x18\x04 \x01(\x03H\x02R\vdateOfBirth\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\x05 \x01(\tH\x03R\x06gender\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x06 \x01(\tH\x04R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\a \x01(\tH\x05R\x05phone\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\b \x01(\tH\x06R\aaddress\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\x10\n" +
	"\x0e_date_of_birthB\t\n" +
	"\a_genderB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phoneB\n" +
	"\n" +
	"\b_address\"\xa9\x02\n" +
	"\x0eClientResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x04 \x01(\x03R\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x12\n" +
	"\x04jmbg\x18\t \x01(\tR\x04jmbg\x12\x16\n" +
	"\x06active\x18\n" +
	" \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"T\n" +
	" ValidateClientCredentialsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x85\x01\n" +
	"!ValidateClientCredentialsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\"X\n" +
	"\x18SetClientPasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\"5\n" +
	"\x19SetClientPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xad\x04\n" +
	"\rClientService\x12C\n" +
	"\fCreateClient\x12\x1b.client.CreateClientRequest\x1a\x16.client.ClientResponse\x12=\n" +
	"\tGetClient\x12\x18.client.GetClientRequest\x1a\x16.client.ClientResponse\x12K\n" +
	"\x10GetClientByEmail\x12\x1f.client.GetClientByEmailRequest\x1a\x16.client.ClientResponse\x12F\n" +
	"\vListClients\x12\x1a.client.ListClientsRequest\x1a\x1b.client.ListClientsResponse\x12C\n" +
	"\fUpdateClient\x12\x1b.client.UpdateClientRequest\x1a\x16.client.ClientResponse\x12j\n" +
	"\x13ValidateCredentials\x12(.client.ValidateClientCredentialsRequest\x1a).client.ValidateClientCredentialsResponse\x12R\n" +
	"\vSetPassword\x12 .client.SetClientPasswordRequest\x1a!.client.SetClientPasswordResponseB/Z-github.com/exbanka/contract/clientpb;clientpbb\x06proto3"

var (
	file_client_client_proto_rawDescOnce sync.Once
	file_client_client_proto_rawDescData []byte
)

func file_client_client_proto_rawDescGZIP() []byte {
	file_client_client_proto_rawDescOnce.Do(func() {
		file_client_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_client_proto_rawDesc), len(file_client_client_proto_rawDesc)))
	})
	return file_client_client_proto_rawDescData
}

var file_client_client_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_client_client_proto_goTypes = []any{
	(*CreateClientRequest)(nil),               // 0: client.CreateClientRequest
	(*GetClientRequest)(nil),                  // 1: client.GetClientRequest
	(*GetClientByEmailRequest)(nil),           // 2: client.GetClientByEmailRequest
	(*ListClientsRequest)(nil),                // 3: client.ListClientsRequest
	(*ListClientsResponse)(nil),               // 4: client.ListClientsResponse
	(*UpdateClientRequest)(nil),               // 5: client.UpdateClientRequest
	(*ClientResponse)(nil),                    // 6: client.ClientResponse
	(*ValidateClientCredentialsRequest)(nil),  // 7: client.ValidateClientCredentialsRequest
	(*ValidateClientCredentialsResponse)(nil), // 8: client.ValidateClientCredentialsResponse
	(*SetClientPasswordRequest)(nil),          // 9: client.SetClientPasswordRequest
	(*SetClientPasswordResponse)(nil),         // 10: client.SetClientPasswordResponse
}
var file_client_client_proto_depIdxs = []int32{
	6,  // 0: client.ListClientsResponse.clients:type_name -> client.ClientResponse
	0,  // 1: client.ClientService.CreateClient:input_type -> client.CreateClientRequest
	1,  // 2: client.ClientService.GetClient:input_type -> client.GetClientRequest
	2,  // 3: client.ClientService.GetClientByEmail:input_type -> client.GetClientByEmailRequest
	3,  // 4: client.ClientService.ListClients:input_type -> client.ListClientsRequest
	5,  // 5: client.ClientService.UpdateClient:input_type -> client.UpdateClientRequest
	7,  // 6: client.ClientService.ValidateCredentials:input_type -> client.ValidateClientCredentialsRequest
	9,  // 7: client.ClientService.SetPassword:input_type -> client.SetClientPasswordRequest
	6,  // 8: client.ClientService.CreateClient:output_type -> client.ClientResponse
	6,  // 9: client.ClientService.GetClient:output_type -> client.ClientResponse
	6,  // 10: client.ClientService.GetClientByEmail:output_type -> client.ClientResponse
	4,  // 11: client.ClientService.ListClients:output_type -> client.ListClientsResponse
	6,  // 12: client.ClientService.UpdateClient:output_type -> client.ClientResponse
	8,  // 13: client.ClientService.ValidateCredentials:output_type -> client.ValidateClientCredentialsResponse
	10, // 14: client.ClientService.SetPassword:output_type -> client.SetClientPasswordResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_client_client_proto_init() }
func file_client_client_proto_init() {
	if File_client_client_proto != nil {
		return
	}
	file_client_client_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_client_proto_rawDesc), len(file_client_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_client_proto_goTypes,
		DependencyIndexes: file_client_client_proto_depIdxs,
		MessageInfos:      file_client_client_proto_msgTypes,
	}.Build()
	File_client_client_proto = out.File
	file_client_client_proto_goTypes = nil
	file_client_client_proto_depIdxs = nil
}
